config/routes.rb
ResourceMap::Application.routes.draw do

  # devise_for :users, :controllers => {:registrations => "registrations", :sessions => 'sessions' }
  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: "omniauth_callbacks"}
  guisso_for :user

  # match 'messaging' => 'messaging#index'
  match 'nuntium' => 'nuntium#receive', :via => :post
  match 'authenticate' => 'nuntium#authenticate', :via => :post
  match 'android/collections' => 'android#collections_json', :via => :get
  match 'android/submission' => 'android#submission', :via => :post
  match 'collections/breadcrumbs' => 'collections#render_breadcrumbs', :via => :post
  match 'real-time-resource-tracking' => 'home#second_page', :via => :get
  match 'track-medical-supplies-and-personnel'=> 'home#medical_page', :via => :get
  match 'track-food-prices-and-supplies' => 'home#food_page', :via => :get
  match 'collections/alerted-collections' => 'collections#alerted_collections', :via => :get
  #match 'analytics' => 'analytics#index', :via => :get
  get 'download/activity' => "activities#download"
  match 'get_user_auth_token' => "application#get_user_auth_token", :via => 'get'
  match 'load_app_cache' => 'home#load_app_cache', :via => 'get'
  get 'plugin/alerts/thresholds' => 'thresholds#index'
  get 'channels_accesses/search_user'
  get 'channels_accesses/search_collection'

  resources :repeats
  resources :collections do
    post  :send_new_member_sms
    post :register_gateways
    get  :message_quota
    get :sites_by_term
    resources :sites do
      get :visible_layers_for
    end
    resources :layers do

      member do
        put :set_order
      end

      collection do
        post :upload_layers
        get :adjust_layers
        get :pending_layers
      end
    end
    resources :fields

    resources :memberships do
      collection do
        get 'invitable'
        get 'search'
      end
      member do
        post 'set_layer_access'
        post 'set_admin'
        post 'unset_admin'
      end
    end
    resources :sites_permission

    resources :reports do
      collection do
        get 'download'
        get 'report'
        get 'get_monthly_graph'
        get 'monthly_graph'
        get 'weekly_graph'
        get 'get_weekly_graph'
      end
    end
    resources :places do
      get 'all'
      collection do
        post 'create_memberships'
        post 'create_hierarchy'
        put 'update_hierarchy'
        delete 'delete_membership'
        get 'memberships'
        get 'download_template'
        get 'download'
        get 'my_supervision_place'
        resource :import_hierarchy_wizard, only: [] do
           get 'index'
           post 'upload_xls'
           get 'adjustments'
           get 'guess_columns_spec'
           post 'execute'
           post 'validate_sites_with_columns'
           get 'get_visible_sites/:page' => 'import_wizards#get_visible_sites'
           get 'import_in_progress'
           get 'import_finished'
           get 'import_failed'
           get 'job_status'
           get 'cancel_pending_jobs'
           get 'logs'
           get 'places'
           get 'memberships'
        end
      end
    end

    get 'members'
    get 'settings'
    get 'quotas'
    get 'csv_template'
    get 'max_value_of_property'

    post 'upload_csv'

    post 'create_snapshot'
    post 'load_snapshot'
    post 'unload_current_snapshot'

    get 'recreate_index'
    get 'search'
    post 'decode_hierarchy_csv'
    post 'decode_location_csv'

    get 'sites_info'

    resource :import_wizard, only: [] do
       get 'index'
       post 'upload_csv'
       get 'adjustments'
       get 'guess_columns_spec'
       post 'execute'
       post 'validate_sites_with_columns'
       get 'get_visible_sites/:page' => 'import_wizards#get_visible_sites'
       get 'import_in_progress'
       get 'import_finished'
       get 'import_failed'
       get 'job_status'
       get 'cancel_pending_jobs'
       get 'logs'
    end
  end

  resources :sites do
    get 'root_sites'
    get 'search', :on => :collection
    get 'search_alert_site', :on => :collection

    post 'update_property'
  end

  resources :messages, :only => [:index], :path => 'message'
  resources :activities, :only => [:index], :path => 'activity'
  resources :quotas
  resources :channels_accesses

  resources :gateways do
    post 'status', :on => :member
    post 'try'
  end

  match 'terms_and_conditions' => redirect("http://instedd.org/terms-of-service/"), :via => :get

  namespace :api do
    get 'collections/:id' => 'collections#show',as: :collection
    get 'collections/:id/export_layers' => 'collections#export_layers', as: :export_layers
    get 'collections/:id/download_location_csv' => 'collections#download_location_csv', as: :download_location_csv
    get 'collections/:id/sample_csv' => 'collections#sample_csv',as: :sample_csv
    get 'collections/:id/count' => 'collections#count',as: :count
    get 'collections/:id/geo' => 'collections#geo_json',as: :geojson
    get 'sites/:id' => 'sites#show', as: :site
    get 'activity' => 'activities#index', as: :activity
    # match 'collections/:id/update_sites_under_collection' => 'collections#update_sites_under_collection', :via => :put
    # put 'collections/:id/update_sites_under_collection' => 'collections#update_sites_under_collection', as: :collections
    resources :tokens, :only => [:index, :destroy]
    resources :collections do
      get 'sites_by_term'
      member do
        put 'update_sites'
        get 'get_fields'
        get 'get_sites_conflict'
        get 'get_some_sites'
      end
      resources :fields, only: [:index]
      resources :sites
    end
    match 'collections/:collection_id/memberships' => 'memberships#create', :via => :post
    match 'collections/:collection_id/memberships' => 'memberships#update', :via => :put
    match 'collections/:collection_id/register_new_member' => 'memberships#register_new_member', :via => :post
    match 'collections/:collection_id/destroy_member' => 'memberships#destroy_member', :via => :delete

    devise_scope :user do
      post '/users' => 'registrations#create'
      post '/users/sign_in' => 'sessions#create'
      post '/users/sign_out' => 'sessions#destroy'
    end

    # v1
    namespace :v1 do
      resources :collections do
        resources :sites, only: [:create,:index,:update, :show] do
          get :visible_layers_for, on: :member
          collection do
            get 'get_site_by_week_year_place'
          end
        end
        resources :memberships, only: [:index] do
          collection do
            get 'search'
          end
        end
        resources :fields, only: [:create,:index,:update,:show]
        resources :layer_memberships, only: [:create,:index,:update,:show]
        resources :site_permissions, only: [:create,:index,:update,:show]
        resources :places do
          collection do
            get 'my_supervision_place'
            get 'get_parent_place_by_ancestry_id'
            get 'memberships'
          end
        end
      end
      namespace :admin do
        resources :collections
      end
    end

    # v2
    namespace :v2 do
      resources :collections, except: [:update] do
        resources :memberships, only: [:index, :create, :destroy] do
          member do
            post :set_admin
            post :unset_admin
          end
          collection do
            get 'invitable'
          end
        end

        resources :layers, except: [:show, :new, :edit] do
          resources :fields, only: [:create]
        end

        resources :fields, only: [:index] do
          collection do
            get 'mapping'
          end
        end

        member do
          get 'sample_csv', as: :sample_csv
          get 'count', as: :count
          get 'geo', as: :geojson, to: "collections#geo_json"
          post 'sites', to: 'sites#create'
          post 'update_sites', to: 'collections#bulk_update'
        end
      end

      resources :sites, only: [:show, :destroy, :update] do
        member do
          post :update_property
          post :partial_update
        end
      end
      get 'histogram/:field_id', to: 'collections#histogram_by_field', as: :histogram_by_field
      get 'collections/:collection_id/sites/:id/histories' => 'sites#histories', as: :histories
      get 'activity' => 'activities#index', as: :activity
      resources :tokens, :only => [:index, :destroy]
    end
  end

  namespace :mobile do
    resources :collections do
      resources :sites do
        get :visible_layers_for, on: :member
      end
      resources :sites_permission
      match 'create_offline_site' => 'sites#create_offline_site', :via => :post
    end
    match 'collections/:collection_id/sites/:id/update_offline_site' => 'sites#update_offline_site', :via => :put
  end

  scope '/plugin' do
    Plugin.all.each do |plugin|
      scope plugin.name do
        plugin.hooks[:routes].each { |plugin_routes_block| instance_eval &plugin_routes_block }
      end
    end
  end

  root :to => 'home#index'

  admin_constraint = lambda do |request|
    request.env['warden'].authenticate? and request.env['warden'].user.is_super_user?
  end

  constraints admin_constraint do
    mount Resque::Server, :at => "/admin/resque"
    match 'analytics' => 'analytics#index', :via => :get
    match 'quota' => 'quota#index', via: :get
  end

  offline = Rack::Offline.configure do
    cache "assets/mobile.js"
    cache "assets/mobile.css"

    cache "assets/jquery.mobile-1.3.2.js"
    cache "assets/jquery.mobile-1.3.2.css"

    cache "assets/images/ajax-loader.gif"
    cache "assets/images/icons-18-white.png"
    cache "assets/images/icons-36-white.png"

    cache "images/add.png"
    cache "images/remove.ico"
    cache "images/favicon.ico"
    network "*"
  end
  match "/application.manifest" => offline, :via => :get

  # TODO: deprecate later

app/controllers/api/collections_controller.rb
class Api::CollectionsController < ApplicationController
  include Api::JsonHelper
  include Api::GeoJsonHelper
  include Concerns::CheckApiDocs

  before_filter :authenticate_api_user!
  skip_before_filter  :verify_authenticity_token

  def index
    render json: current_user.collections, :root => false
  end

  def show
    options = [:sort]

    if params[:format] == 'csv' || params[:page] == 'all'
      options << :all
      params.delete(:page)
    elsif params[:format] == 'kml' || params[:format] == 'shp'
      options << :require_location
      options << :page
    else
      options << :page
    end
    @results = perform_search *options

    collection.time_zone = current_user.time_zone
    respond_to do |format|
      format.rss { render :show, layout: false }
      format.csv { collection_csv(collection, @results) }
      format.json { render json: collection_json(collection, @results) }
      format.kml { collection_kml(collection, @results) }
      format.shp { collection_shp(collection, @results) }
    end
  end
  
  def export_layers   
    respond_to do |format|
      format.json {send_data layers.to_json(include: :fields.as_json(:except => [:id]), :except => [:id, :ord, :collection_id]), filename: "#{collection.name}_layers.json"}
    end
  end

  def download_location_csv
    field = fields.find(params[:field])
    location_csv = collection.location_csv(field.config["locations"]) if field.config["locations"]
    send_data location_csv, type: 'text/csv', filename: "#{field.name}_locations.csv"
  end

  def sample_csv
    respond_to do |format|
      format.csv { collection_sample_csv(collection) }
    end
  end

  def collection_sample_csv(collection)
    sample_csv = collection.sample_csv current_user
    send_data sample_csv, type: 'text/csv', filename: "#{collection.name}_sites.csv"
  end

  def count
    render json: perform_search(:count).total
  end

  def geo_json
    @results = perform_search :page, :sort, :require_location
    render json: collection_geo_json(collection, @results)
  end

  def update_sites
    index = 0
    array_site_ids = params[:site_id].split(",")
    array_user_email = params[:user_email].split(",")
    array_site_ids.each do |el|
      site = Site.find_by_id(el)
      site.user = User.find_by_email(array_user_email[index])
      site.user = User.first
      site.lat = params[:lat]
      site.lng = params[:lng]
      if site.valid?
        site.save!
      else
        render json: site.errors.messages, status: :unprocessable_entity, :layout => false
      end
      index = index + 1
    end
    render json: {status: 201}
  end

  def get_fields
    fields = Collection.find(params[:id]).fields
    list = []
    fields.each do |f|
      obj = {}
      obj["code"] = f.code
      obj["id"] = f.id
      obj["name"] = f.name
      obj["kind"] = f.kind
      obj["options"] = f.config["options"] if f.config["options"]
      list.push obj
    end
    render :json => list.to_json
  end

  def get_sites_conflict
    if params[:con_type]
      sites = []
      con_type = params[:con_type].split(",")
      collection = Collection.find_by_id(params[:id])
      properties = collection.fields.find_by_code(params[:field_code]).id
      if (params[:from].blank? && params[:to].blank?)
        from = parse_date_format("#{Time.now.mon}/01/#{Time.now.year}") - 1
        to = parse_date_format("#{Time.now.mon}/30/#{Time.now.year}").end_of_month + 1
        tmp_sites = Collection.find(params[:id]).sites.where(:created_at => from..to).each do |x|
          con_type.each do |el|
            if x.properties["#{properties}"] == el.to_i
              sites << x
            end
          end
        end
      else
        from = parse_date_format(params[:from]) - 1
        to = parse_date_format(params[:to]) + 1
        tmp_sites = Collection.find(params[:id]).sites.where(:created_at => from..to).each do |x|
          con_type.each do |el|
            if x.properties["#{properties}"] == el.to_i
              sites << x
            end
          end
        end
      end  
    else
      sites = Collection.find(params[:id]).sites
    end
    render :json => sites
  end

  def get_some_sites
    site_ids = params[:sites]
    sites = Site.where("id in (" + site_ids + ")")
    render :json => sites
  end

  def parse_date_format date 
    array_date = date.split("-")
    return Date.new(array_date[2].to_i, array_date[0].to_i, array_date[1].to_i)
  end

  def sites_by_term
    search = new_search

    search.full_text_search params[:term] if params[:term]
    search.alerted_search params[:_alert] if params[:_alert] 
    search.select_fields(['id', 'name', 'properties'])
    # search.apply_queries
    unless current_user.admins? collection
      place = HierarchyMembership.find_by_user_id(current_user.id).place
      search.place_in(place.subtree_ids)
    end
    results = search.results.map{ |item| item["fields"]}

    results.each do |item|
      item[:value] = item["name"]
    end

    render json: results
  end

  private

  def perform_search(*options)

    except_params = [:action, :controller, :format, :id, :updated_since, :search, :box, :lat, :lng, :radius]

    search = new_search

    search.use_codes_instead_of_es_codes

    if options.include? :page
      search.page params[:page].to_i if params[:page]
      except_params << :page
    elsif options.include? :count
      search.offset 0
      search.limit 0
    elsif options.include? :all
      search.unlimited
    end
    unless current_user.admins? collection
      place = HierarchyMembership.find_by_user_id(current_user.id).place
      search.place_in(place.subtree_ids)
    end
    search.after params[:updated_since] if params[:updated_since]
    search.full_text_search params[:search] if params[:search]
    search.box *valid_box_coordinates if params[:box]

    if params[:lat] || params[:lng] || params[:radius]
      [:lat, :lng, :radius].each do |key|
        raise "Missing '#{key}' parameter" unless params[key]
        raise "Missing '#{key}' value" unless !params[key].blank?

      end
      search.radius params[:lat], params[:lng], params[:radius]
    end

    if options.include? :require_location
      search.require_location
    end

    if options.include? :sort
      search.sort params[:sort], params[:sort_direction] != 'desc' if params[:sort]
      except_params << :sort
      except_params << :sort_direction
    end
    search.where params.except(*except_params)
    search.api_results
  end

  def valid_box_coordinates
    coords = params[:box].split ','
    raise "Expected the 'box' parameter to be four comma-separated numbers" if coords.length != 4

    coords.each_with_index do |coord, i|
      Float(coord) rescue raise "Expected #{(i + 1).ordinalize} value of 'box' parameter to be a number, not '#{coord}'"
    end

    coords
  end

  def collection_csv(collection, results)
    sites_csv = collection.to_csv results, current_user
    send_data sites_csv, type: 'text/csv', filename: "#{collection.name}_sites.csv"
  end

  def collection_shp(collection, results)
    send_data collection.to_shp(results), type: 'application/zip', filename: "#{collection.id}.zip"
  end

  def collection_kml(collection, results)
    sites_kml = collection.to_kml results
    send_data sites_kml, type: 'application/vnd.google-earth.kml+xml', filename: "#{collection.name}_sites.kml"
  end

  def visible_layer_for_site    
    
  end

end

app/views/collections/_form.haml
= form_for collection do |f|
  :javascript
    $(document).ready(function(){ 
      var ori_checked = $("#collection_hierarchy_mode").attr("checked");
      if (ori_checked == undefined){
        $("#hierachy_mode_options").hide();
      }
      var select_icon = $('#select_icon');
      if(select_icon.val() == "")
        select_icon.val('default');
      $("#focus_icon").val(select_icon.val());
      $('.' + select_icon.val()).css({backgroundColor: '#D2D2D2', border: '1px solid #565656'});

      $("button").click(function(){
        if (this != $('.white')[0]){
          $('#select_icon').val($("#focus_icon").val());
          $('.' + $('#focus_icon').val()).css({backgroundColor: '#f5f5f5', border: '1px solid white'});
          this.style.backgroundColor =  "#D2D2D2";
          this.style.border =  "1px solid #565656";
          
          $("#focus_icon").val(this.classList["0"]);

        }else{
          $('#select_icon').val($("#focus_icon").val());
        }
      });

      $("#collection_hierarchy_mode").click(function(){
        var ori_checked = $("#collection_hierarchy_mode").attr("checked");
        if (ori_checked){
          $("#hierachy_mode_options").show();
        }else{
          $("#hierachy_mode_options").hide();
          $("#collection_field_identify").val("");
          $("#collection_field_parent").val("");
        }
      })
    });
  
  .field.w60
    = f.label t('views.collections.form.name') 
    = f.text_field :name, :readonly => !creation && (cannot? :update, collection)
    - if f.object.errors[:name].present?
      %label.error= "Name #{f.object.errors[:name].join(', ')}"
  .field.w60
    = f.label t('views.collections.form.description') 
    = f.text_area :description, rows: 3, :readonly =>  !creation && (cannot? :update, collection)
  - if Settings.is_on? :public_collection
    .field.w60
      = f.label t('views.collections.form.public') 
      = f.check_box :public, :disabled => !creation && (cannot? :update, collection)

  - if !creation 
    .field.w60
      = f.label t('views.collections.form.hierarchy_mode') 
      = f.check_box :hierarchy_mode, :disabled => !creation && (cannot? :update, collection)

    .field.w60#hierachy_mode_options
      = f.label t('views.collections.form.field_identify')
      = f.select :field_identify, options_for_select(@options_for_select, collection.field_identify), {}, :disabled => !creation && (cannot? :update, collection) 
      = f.label t('views.collections.form.field_parent')
      = f.select :field_parent, options_for_select(@options_for_select, collection.field_parent), {}, :disabled => !creation && (cannot? :update, collection) 

  .field.w60
    %label
      = t('views.collections.form.icon') 
    = render 'icon_selector', :f => f
  .w60
  %br{clear: :all}

  - if (creation || can?(:update, collection))
    = f.button t('views.collections.form.save') , :class => 'white'
    = link_to t('views.collections.form.cancel'), collections_path, :class=> 'grey'

app/views/collections/_hierarchy_mode.haml
%label Field Identify
%select.w25#field_identify_hierarchy_mode{ko(value: :value, options: :optionsUIIds, optionsText: 'function(o){return $data.labelFor(o)}')}
%label Field Parent
%select.w25#field_parent_hierarchy_mode

app/views/collections/_icon_selector.haml
= f.hidden_field :icon, id: 'select_icon'
%input#focus_icon{:type =>"hidden"}

%button.default{:type => "button"}
%button.aed-2{:type => "button"}
%button.construction{:type => "button"}
%button.daycare{:type => "button"}
%button.drugstore{:type => "button"}
%button.fetalalcoholsyndrom{:type => "button"}
%button.firstaid{:type => "button"}
%button.hospital-building{:type => "button"}
%button.medicine{:type => "button"}
%button.nanny{:type => "button"}
%button.nursery{:type => "button"}
%button.villa{:type => "button"}
%br
%br
%br
%button.army{:type => "button"}
%button.bomber-2{:type => "button"}
%button.chemistry-2{:type => "button"}
%button.constructioncrane{:type => "button"}
%button.cycling{:type => "button"}
%button.dentist{:type => "button"}
%button.disability{:type => "button"}
%button.factory{:type => "button"}
%button.fishing{:type => "button"}
%button.foodtruck{:type => "button"}
%button.footprint{:type => "button"}
%button.fourbyfour{:type => "button"}
%br
%br
%br
%button.gay-female{:type => "button"}
%button.gay-male{:type => "button"}
%button.highschool{:type => "button"}
%button.school{:type => "button"}
%button.university{:type => "button"}
%button.hiking{:type => "button"}
%button.horseriding{:type => "button"}
%button.hostel_0star{:type => "button"}
%button.hotel_0star{:type => "button"}
%button.lodging_0star{:type => "button"}
%button.motel-2{:type => "button"}
%button.youthhostel{:type => "button"}
%br
%br
%br
%button.mastcrane1{:type => "button"}
%button.ophthalmologist{:type => "button"}
%button.powerlinepole{:type => "button"}
%button.poweroutage{:type => "button"}
%button.powerplant{:type => "button"}
%button.powersubstation{:type => "button"}
%button.radio-station-2{:type => "button"}
%button.windturbine{:type => "button"}
%button.mobilephonetower{:type => "button"}
%button.restaurant_fish{:type => "button"}
%button.sawmill-2{:type => "button"}
%button.mine{:type => "button"}
%br
%br
%br
%button.septic_tank{:type => "button"}
%button.shootingrange{:type => "button"}
%button.hunting{:type => "button"}
%button.solarenergy{:type => "button"}
%button.sozialeeinrichtung{:type => "button"}
%button.summercamp{:type => "button"}
%button.veterinary{:type => "button"}
%button.watertower{:type => "button"}
%button.wifi{:type => "button"}
%button.medicalstore{:type => "button"}
%button.recycle{:type => "button"}
%button.resort{:type => "button"}
%br
%br
%br

app/views/collections/_snapshot.haml
%hr.clear/
%h2(id='snapshots')= t('views.collections.overview.snapshots')
%p= t('views.collections.overview.snapshots_description')
- if collection_admin?

  = form_for(@snapshot, :url => collection_create_snapshot_path(collection)) do |f|
    %span.snapshot_name_field.w30
      = f.text_field :name, :placeholder => t('views.collections.overview.enter_snapshot_name')
      - if f.object.errors[:name].present?
        %br/
        %label.error= t('views.collections.form.errors.name', errors: f.object.errors[:name].join(', '))
    %button.icon_button.fsnapshot
      = t('views.collections.overview.take_new_snapshot')

- if collection.snapshots.count > 0
  %table
    %tr
      = form_tag(collection_unload_current_snapshot_path(collection)) do
        %td.w30
          .snapshot_info{:class => if current_user_snapshot.at_present? then "active rounded" end}
            = radio_button_tag(:name, "", current_user_snapshot.at_present?, :onclick => "this.form.submit();")
            = label :name, t('views.collections.overview.present_time')
        %td

    - collection.snapshots.each do |snapshot|
      %tr
        = form_tag(collection_load_snapshot_path(collection)) do
          - is_current_snapshot = !current_user_snapshot.at_present? && current_user_snapshot.snapshot.name == snapshot.name
          %td.w30
            .snapshot_info{:class => if is_current_snapshot then "active rounded" end}
              = radio_button_tag(:name, snapshot.name, is_current_snapshot, :onclick => "this.form.submit();")
              = label :name, snapshot.name
          %td.grey
            = label_tag :date, snapshot.date.rfc822
- elsif !collection_admin?
  = t('views.collections.overview.no_snapshots')

%br/
%br/

app/views/collections/decode_hierarchy_csv.haml
:javascript
  #{@hierarchy.any? do |m| m[:error] end ? "parent.window.model.errorUploadingHierarchy('#{j @hierarchy_errors}');" : "parent.window.model.hierarchyUploaded(#{@hierarchy.to_json});" }

app/views/collections/decode_location_csv.haml
:javascript
  #{@locations.any? do |m| m[:error] end ? "parent.window.model.errorUploadingLocation('#{j @locations_errors}');" : "parent.window.model.locationUploaded(#{@locations.to_json});" }

app/views/collections/index.haml
- content_for :head do
  = google_maps_javascript_include_tag
  :javascript
    var currentUserIsGuest = #{!!current_user.is_guest};

<!-- ko if: !fullscreen() -->
%h1
  = t('views.collections.index.collections')
  %p#snapshot_loaded_message{style: 'display:none'}
    <!-- ko if: currentSnapshot() -->
    <!-- ko with: currentCollection -->
    %span.i18g-snapshot
    %span{ko(text: :viewingCurrentSnapshotMessage )}
    %a{ko(click: :unloadCurrentSnapshot)}
      = t('views.collections.index.go_back_to_present')
    <!-- /ko -->
    <!-- /ko -->
<!-- /ko -->

= render 'collections/index/refine_hierarchy_items_template'
= render 'collections/index/field_hierarchy_items_template'
= render 'collections/index/map_sites_template'
= render 'collections/index/map_hierarchy_items_template'
= render 'collections/index/map_hierarchy_sites_template'
= render 'collections/index/table_sites_template'
= render 'collections/index/table_hierarchy_items_template'

#refine-container{style: 'display:none'}
  <!-- ko if: currentCollection() -->
  = render 'collections/index/refine'
  <!-- /ko -->

= render 'collections/index/download_dialog'
#collections-dummy{style: 'height:600px'}
#collections-main.box.slightly-padded.h50{style: 'display:none'}

  <!-- ko if: showingMap() -->
  = render 'collections/index/map'
  <!-- /ko -->

  <!-- ko if: !showingMap() -->
  = render 'collections/index/table'
  <!-- /ko -->

  .clear
<br/>
%div{'align' => 'right'}
  = link_to t('views.collections.index.mobile_version'), mobile_collections_path, {:style => 'color: #555555;'}

app/views/collections/new.haml
%h2= t('views.collections.index.new')
%p= t('views.collections.index.description')
%br/

= render 'form', creation: true

app/views/collections/show.haml
= render '/tabs'

- sites_count = if !current_user_snapshot.at_present? then collection.site_histories.at_date(current_user_snapshot.snapshot.date).count else collection.sites.count end

.tabsline
  %h2= t('views.collections.overview.status')
  %div
    .sbox.grey.w30.sitesBox
      .left.sitesDescription
        .sitesCount= sites_count
        = t('views.collections.overview.sites')
      %button.csvDownload.white.right{type: "button", |
          onclick: "window.location = '#{sites_count == 0 ? api_sample_csv_path(collection, format: 'csv') : api_collection_path(collection, format: 'csv', auth_token: current_user.authentication_token)}'"}
        = if sites_count == 0 then t('views.collections.overview.download_sample_csv') else t('views.collections.overview.download_as_csv') end
    %div
      = link_to t('views.collections.overview.upload_it_for_bulk_sites_updates'), collection_import_wizard_path(collection), class: 'icon fexport black'
  %hr.clear/
  %h2 API access
  %p{style: 'margin:-8px 0 8px 0'}
    = t('views.collections.overview.access_the_api_in')
    #{link_to 'RSS', api_collection_path(collection, format: :rss), target: :_blank},
    #{link_to 'JSON', api_collection_path(collection, format: :json), target: :_blank},
    #{link_to 'CSV', api_collection_path(collection, format: :csv), target: :_blank},
    = t('views.collections.overview.or')
    #{link_to 'SHP', api_collection_path(collection, format: :shp), target: :_blank}.
    = t('views.collections.overview.check_the')
    #{link_to 'API documentation', 'https://bitbucket.org/instedd/resource_map/wiki/REST_API', target: :_blank}
    %br/
    %br/

  - if Settings.is_on? :snapshot
    = render 'snapshot'

  %hr.clear/

  - if collection_admin?
    .delete-collection-or-sites
      .left
        = render './confirm_box', :action_code => 'delete-collection-sites', :action_description => t('views.collections.overview.delete_collection_sites'), :icon_class => 'fclose', :confirm_action_prompt => t('views.collections.overview.delete_collection_sites_prompt'), :action_url => collection_path(only_sites: true)

      .left
        = render './confirm_box', :action_code => 'delete-collection', :action_description => t('views.collections.overview.delete_collection'), :icon_class => 'fdelete', :confirm_action_prompt => t('views.collections.overview.delete_collection_prompt'), :action_url => collection_path