config/routes.rb
ResourceMap::Application.routes.draw do

  # devise_for :users, :controllers => {:registrations => "registrations", :sessions => 'sessions' }
  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: "omniauth_callbacks"}
  guisso_for :user

  # match 'messaging' => 'messaging#index'
  match 'nuntium' => 'nuntium#receive', :via => :post
  match 'authenticate' => 'nuntium#authenticate', :via => :post
  match 'android/collections' => 'android#collections_json', :via => :get
  match 'android/submission' => 'android#submission', :via => :post
  match 'collections/breadcrumbs' => 'collections#render_breadcrumbs', :via => :post
  match 'real-time-resource-tracking' => 'home#second_page', :via => :get
  match 'track-medical-supplies-and-personnel'=> 'home#medical_page', :via => :get
  match 'track-food-prices-and-supplies' => 'home#food_page', :via => :get
  match 'collections/alerted-collections' => 'collections#alerted_collections', :via => :get
  #match 'analytics' => 'analytics#index', :via => :get
  get 'download/activity' => "activities#download"
  match 'get_user_auth_token' => "application#get_user_auth_token", :via => 'get'
  match 'load_app_cache' => 'home#load_app_cache', :via => 'get'
  get 'plugin/alerts/thresholds' => 'thresholds#index'
  get 'channels_accesses/search_user'
  get 'channels_accesses/search_collection'

  resources :repeats
  resources :collections do
    post  :send_new_member_sms
    post :register_gateways
    get  :message_quota
    get :sites_by_term
    resources :sites do
      get :visible_layers_for
    end
    resources :layers do

      member do
        put :set_order
      end

      collection do
        post :upload_layers
        get :adjust_layers
        get :pending_layers
      end
    end
    resources :fields

    resources :memberships do
      collection do
        get 'invitable'
        get 'search'
      end
      member do
        post 'set_layer_access'
        post 'set_admin'
        post 'unset_admin'
      end
    end
    resources :sites_permission

    resources :reports do
      collection do
        get 'download'
        get 'report'
        get 'get_monthly_graph'
        get 'monthly_graph'
        get 'weekly_graph'
        get 'get_weekly_graph'
      end
    end
    resources :places do
      get 'all'
      collection do
        post 'create_memberships'
        post 'create_hierarchy'
        put 'update_hierarchy'
        delete 'delete_membership'
        get 'memberships'
        get 'download_template'
        get 'download'
        get 'my_supervision_place'
        resource :import_hierarchy_wizard, only: [] do
           get 'index'
           post 'upload_xls'
           get 'adjustments'
           get 'guess_columns_spec'
           post 'execute'
           post 'validate_sites_with_columns'
           get 'get_visible_sites/:page' => 'import_wizards#get_visible_sites'
           get 'import_in_progress'
           get 'import_finished'
           get 'import_failed'
           get 'job_status'
           get 'cancel_pending_jobs'
           get 'logs'
           get 'places'
           get 'memberships'
        end
      end
    end

    get 'members'
    get 'settings'
    get 'quotas'
    get 'csv_template'
    get 'max_value_of_property'

    post 'upload_csv'

    post 'create_snapshot'
    post 'load_snapshot'
    post 'unload_current_snapshot'

    get 'recreate_index'
    get 'search'
    post 'decode_hierarchy_csv'
    post 'decode_location_csv'

    get 'sites_info'

    resource :import_wizard, only: [] do
       get 'index'
       post 'upload_csv'
       get 'adjustments'
       get 'guess_columns_spec'
       post 'execute'
       post 'validate_sites_with_columns'
       get 'get_visible_sites/:page' => 'import_wizards#get_visible_sites'
       get 'import_in_progress'
       get 'import_finished'
       get 'import_failed'
       get 'job_status'
       get 'cancel_pending_jobs'
       get 'logs'
    end
  end

  resources :sites do
    get 'root_sites'
    get 'search', :on => :collection
    get 'search_alert_site', :on => :collection

    post 'update_property'
  end

  resources :messages, :only => [:index], :path => 'message'
  resources :activities, :only => [:index], :path => 'activity'
  resources :quotas
  resources :channels_accesses

  resources :gateways do
    post 'status', :on => :member
    post 'try'
  end

  match 'terms_and_conditions' => redirect("http://instedd.org/terms-of-service/"), :via => :get

  namespace :api do
    get 'collections/:id' => 'collections#show',as: :collection
    get 'collections/:id/export_layers' => 'collections#export_layers', as: :export_layers
    get 'collections/:id/download_location_csv' => 'collections#download_location_csv', as: :download_location_csv
    get 'collections/:id/sample_csv' => 'collections#sample_csv',as: :sample_csv
    get 'collections/:id/count' => 'collections#count',as: :count
    get 'collections/:id/geo' => 'collections#geo_json',as: :geojson
    get 'sites/:id' => 'sites#show', as: :site
    get 'activity' => 'activities#index', as: :activity
    # match 'collections/:id/update_sites_under_collection' => 'collections#update_sites_under_collection', :via => :put
    # put 'collections/:id/update_sites_under_collection' => 'collections#update_sites_under_collection', as: :collections
    resources :tokens, :only => [:index, :destroy]
    resources :collections do
      get 'sites_by_term'
      member do
        put 'update_sites'
        get 'get_fields'
        get 'get_sites_conflict'
        get 'get_some_sites'
      end
      resources :fields, only: [:index]
      resources :sites
    end
    match 'collections/:collection_id/memberships' => 'memberships#create', :via => :post
    match 'collections/:collection_id/memberships' => 'memberships#update', :via => :put
    match 'collections/:collection_id/register_new_member' => 'memberships#register_new_member', :via => :post
    match 'collections/:collection_id/destroy_member' => 'memberships#destroy_member', :via => :delete

    devise_scope :user do
      post '/users' => 'registrations#create'
      post '/users/sign_in' => 'sessions#create'
      post '/users/sign_out' => 'sessions#destroy'
    end

    # v1
    namespace :v1 do
      resources :collections do
        resources :sites, only: [:create,:index,:update, :show] do
          get :visible_layers_for, on: :member
          collection do
            get 'get_site_by_week_year_place'
          end
        end
        resources :memberships, only: [:index] do
          collection do
            get 'search'
          end
        end
        resources :fields, only: [:create,:index,:update,:show]
        resources :layer_memberships, only: [:create,:index,:update,:show]
        resources :site_permissions, only: [:create,:index,:update,:show]
        resources :places do
          collection do
            get 'my_supervision_place'
            get 'get_parent_place_by_ancestry_id'
            get 'memberships'
          end
        end
      end
      namespace :admin do
        resources :collections
      end
    end

    # v2
    namespace :v2 do
      resources :collections, except: [:update] do
        resources :memberships, only: [:index, :create, :destroy] do
          member do
            post :set_admin
            post :unset_admin
          end
          collection do
            get 'invitable'
          end
        end

        resources :layers, except: [:show, :new, :edit] do
          resources :fields, only: [:create]
        end

        resources :fields, only: [:index] do
          collection do
            get 'mapping'
          end
        end

        member do
          get 'sample_csv', as: :sample_csv
          get 'count', as: :count
          get 'geo', as: :geojson, to: "collections#geo_json"
          post 'sites', to: 'sites#create'
          post 'update_sites', to: 'collections#bulk_update'
        end
      end

      resources :sites, only: [:show, :destroy, :update] do
        member do
          post :update_property
          post :partial_update
        end
      end
      get 'histogram/:field_id', to: 'collections#histogram_by_field', as: :histogram_by_field
      get 'collections/:collection_id/sites/:id/histories' => 'sites#histories', as: :histories
      get 'activity' => 'activities#index', as: :activity
      resources :tokens, :only => [:index, :destroy]
    end
  end

  namespace :mobile do
    resources :collections do
      resources :sites do
        get :visible_layers_for, on: :member
      end
      resources :sites_permission
      match 'create_offline_site' => 'sites#create_offline_site', :via => :post
    end
    match 'collections/:collection_id/sites/:id/update_offline_site' => 'sites#update_offline_site', :via => :put
  end

  scope '/plugin' do
    Plugin.all.each do |plugin|
      scope plugin.name do
        plugin.hooks[:routes].each { |plugin_routes_block| instance_eval &plugin_routes_block }
      end
    end
  end

  root :to => 'home#index'

  admin_constraint = lambda do |request|
    request.env['warden'].authenticate? and request.env['warden'].user.is_super_user?
  end

  constraints admin_constraint do
    mount Resque::Server, :at => "/admin/resque"
    match 'analytics' => 'analytics#index', :via => :get
    match 'quota' => 'quota#index', via: :get
  end

  offline = Rack::Offline.configure do
    cache "assets/mobile.js"
    cache "assets/mobile.css"

    cache "assets/jquery.mobile-1.3.2.js"
    cache "assets/jquery.mobile-1.3.2.css"

    cache "assets/images/ajax-loader.gif"
    cache "assets/images/icons-18-white.png"
    cache "assets/images/icons-36-white.png"

    cache "images/add.png"
    cache "images/remove.ico"
    cache "images/favicon.ico"
    network "*"
  end
  match "/application.manifest" => offline, :via => :get

  # TODO: deprecate later

app/controllers/api/collections_controller.rb
class Api::CollectionsController < ApplicationController
  include Api::JsonHelper
  include Api::GeoJsonHelper
  include Concerns::CheckApiDocs

  before_filter :authenticate_api_user!
  skip_before_filter  :verify_authenticity_token

  def index
    render json: current_user.collections, :root => false
  end

  def show
    options = [:sort]

    if params[:format] == 'csv' || params[:page] == 'all'
      options << :all
      params.delete(:page)
    elsif params[:format] == 'kml' || params[:format] == 'shp'
      options << :require_location
      options << :page
    else
      options << :page
    end
    @results = perform_search *options

    collection.time_zone = current_user.time_zone
    respond_to do |format|
      format.rss { render :show, layout: false }
      format.csv { collection_csv(collection, @results) }
      format.json { render json: collection_json(collection, @results) }
      format.kml { collection_kml(collection, @results) }
      format.shp { collection_shp(collection, @results) }
    end
  end
  
  def export_layers   
    respond_to do |format|
      format.json {send_data layers.to_json(include: :fields.as_json(:except => [:id]), :except => [:id, :ord, :collection_id]), filename: "#{collection.name}_layers.json"}
    end
  end

  def download_location_csv
    field = fields.find(params[:field])
    location_csv = collection.location_csv(field.config["locations"]) if field.config["locations"]
    send_data location_csv, type: 'text/csv', filename: "#{field.name}_locations.csv"
  end

  def sample_csv
    respond_to do |format|
      format.csv { collection_sample_csv(collection) }
    end
  end

  def collection_sample_csv(collection)
    sample_csv = collection.sample_csv current_user
    send_data sample_csv, type: 'text/csv', filename: "#{collection.name}_sites.csv"
  end

  def count
    render json: perform_search(:count).total
  end

  def geo_json
    @results = perform_search :page, :sort, :require_location
    render json: collection_geo_json(collection, @results)
  end

  def update_sites
    index = 0
    array_site_ids = params[:site_id].split(",")
    array_user_email = params[:user_email].split(",")
    array_site_ids.each do |el|
      site = Site.find_by_id(el)
      site.user = User.find_by_email(array_user_email[index])
      site.user = User.first
      site.lat = params[:lat]
      site.lng = params[:lng]
      if site.valid?
        site.save!
      else
        render json: site.errors.messages, status: :unprocessable_entity, :layout => false
      end
      index = index + 1
    end
    render json: {status: 201}
  end

  def get_fields
    fields = Collection.find(params[:id]).fields
    list = []
    fields.each do |f|
      obj = {}
      obj["code"] = f.code
      obj["id"] = f.id
      obj["name"] = f.name
      obj["kind"] = f.kind
      obj["options"] = f.config["options"] if f.config["options"]
      list.push obj
    end
    render :json => list.to_json
  end

  def get_sites_conflict
    if params[:con_type]
      sites = []
      con_type = params[:con_type].split(",")
      collection = Collection.find_by_id(params[:id])
      properties = collection.fields.find_by_code(params[:field_code]).id
      if (params[:from].blank? && params[:to].blank?)
        from = parse_date_format("#{Time.now.mon}/01/#{Time.now.year}") - 1
        to = parse_date_format("#{Time.now.mon}/30/#{Time.now.year}").end_of_month + 1
        tmp_sites = Collection.find(params[:id]).sites.where(:created_at => from..to).each do |x|
          con_type.each do |el|
            if x.properties["#{properties}"] == el.to_i
              sites << x
            end
          end
        end
      else
        from = parse_date_format(params[:from]) - 1
        to = parse_date_format(params[:to]) + 1
        tmp_sites = Collection.find(params[:id]).sites.where(:created_at => from..to).each do |x|
          con_type.each do |el|
            if x.properties["#{properties}"] == el.to_i
              sites << x
            end
          end
        end
      end  
    else
      sites = Collection.find(params[:id]).sites
    end
    render :json => sites
  end

  def get_some_sites
    site_ids = params[:sites]
    sites = Site.where("id in (" + site_ids + ")")
    render :json => sites
  end

  def parse_date_format date 
    array_date = date.split("-")
    return Date.new(array_date[2].to_i, array_date[0].to_i, array_date[1].to_i)
  end

  def sites_by_term
    search = new_search

    search.full_text_search params[:term] if params[:term]
    search.alerted_search params[:_alert] if params[:_alert] 
    search.select_fields(['id', 'name', 'properties'])
    # search.apply_queries
    unless current_user.admins? collection
      place = HierarchyMembership.find_by_user_id(current_user.id).place
      search.place_in(place.subtree_ids)
    end
    results = search.results.map{ |item| item["fields"]}

    results.each do |item|
      item[:value] = item["name"]
    end

    render json: results
  end

  private

  def perform_search(*options)

    except_params = [:action, :controller, :format, :id, :updated_since, :search, :box, :lat, :lng, :radius]

    search = new_search

    search.use_codes_instead_of_es_codes

    if options.include? :page
      search.page params[:page].to_i if params[:page]
      except_params << :page
    elsif options.include? :count
      search.offset 0
      search.limit 0
    elsif options.include? :all
      search.unlimited
    end
    unless current_user.admins? collection
      place = HierarchyMembership.find_by_user_id(current_user.id).place
      search.place_in(place.subtree_ids)
    end
    search.after params[:updated_since] if params[:updated_since]
    search.full_text_search params[:search] if params[:search]
    search.box *valid_box_coordinates if params[:box]

    if params[:lat] || params[:lng] || params[:radius]
      [:lat, :lng, :radius].each do |key|
        raise "Missing '#{key}' parameter" unless params[key]
        raise "Missing '#{key}' value" unless !params[key].blank?

      end
      search.radius params[:lat], params[:lng], params[:radius]
    end

    if options.include? :require_location
      search.require_location
    end

    if options.include? :sort
      search.sort params[:sort], params[:sort_direction] != 'desc' if params[:sort]
      except_params << :sort
      except_params << :sort_direction
    end
    search.where params.except(*except_params)
    search.api_results
  end

  def valid_box_coordinates
    coords = params[:box].split ','
    raise "Expected the 'box' parameter to be four comma-separated numbers" if coords.length != 4

    coords.each_with_index do |coord, i|
      Float(coord) rescue raise "Expected #{(i + 1).ordinalize} value of 'box' parameter to be a number, not '#{coord}'"
    end

    coords
  end

  def collection_csv(collection, results)
    sites_csv = collection.to_csv results, current_user
    send_data sites_csv, type: 'text/csv', filename: "#{collection.name}_sites.csv"
  end

  def collection_shp(collection, results)
    send_data collection.to_shp(results), type: 'application/zip', filename: "#{collection.id}.zip"
  end

  def collection_kml(collection, results)
    sites_kml = collection.to_kml results
    send_data sites_kml, type: 'application/vnd.google-earth.kml+xml', filename: "#{collection.name}_sites.kml"
  end

  def visible_layer_for_site    
    
  end

end

app/views/collections/index/_create_collection.haml
.tablebottom
  %div{ ko(click: '$root.createCollection'), style: 'cursor: pointer;float:left;' }  
    %button.cadd{type: "button"}
    %span.createCollection= t('views.collections.index.create_collection')
    .clear &nbsp;

app/views/collections/index/_create_site.haml
%div
  %div{style: "float:left;"}
    %button.flocation{ko(click: '$root.createSite')}= t('views.collections.index.create_site')
  %div{style: "float: right; margin-top: 6px; margin-right: 6px; "}
    %a{ :href => "javascript:(void)", :"data-bind" => kov(:click => '$root.openDialog'), :id => 'download-dialog', 
                :class => 'white'}= t('views.collections.index.download_history')
  .clear &nbsp;

app/views/collections/index/_download_dialog.haml
%div{ class: "box centered w40 rm-dialog hidden", style: "margin-left: -200px; margin-top: -100px;" }
  =form_tag(download_activity_path, :method => "get" ) do
    %h2= t('views.collections.index.download_history')
    - types = { :month => t('views.collections.index.this_month'),
                :previous_month => t('views.collections.index.previous_month'),
                :all => t('views.collections.index.all') }
    - types.each do |key, value|
      .item
        %input{ type: "radio",  name: "collection[type]",  value: key, id: "collection_type_#{key}"}
        %label{ for: "collection_type_#{key}"}
          = value
          
    %input{"type" => "hidden", "id" => "rm-colllection_id" , "name" => "collection[id]", "value" => "xx" }   
    .item
      %input{type: "radio", checked: 'checked',name: "collection[type]",  value: "range", id: "collection_type_range" }
      %label{for: "collection_type_range"}= t('views.collections.index.custom_range')

    .date_rage{ style: "margin-left: 15px; padding: 10px;" }
      .w15{ style: "float:left;"}
        %label{for: "collection_from"}= t('views.collections.index.from')
        %input{ :type => "text", :name => "collection[from]", :class => "w10 datepicker", :id => "collection_from", :"autocomplete" => "off" }
      .w15{ style: "float:left;"}
        %label{for: "collection_to" }= t('views.collections.index.to')
        %input{ :type => "text", :name => "collection[to]",  :class => "w10 datepicker", :id => "collection_to", :"autocomplete" => "off" }
    %br
    %div{ style: "margin-left: 15px; padding-top: 10px;"}
      %button{ type: "button", value: "Cancel", class: "white rm-dialog-cancel" }= t('views.collections.index.cancel')
      %button{ type: "submit", value: "Download", class: "white rm-dialog-ok" }= t('views.collections.index.download')
    .clear &nbsp;

:javascript
  $(function(){
    
    $.fn.rmDialog = function(options){
  
        return this.each(function(){
            $(this).show();
            dialog = $(this);
            $(this).find(".rm-dialog-cancel").on("click", function(){
                dialog.hide();
            });
        });
    }
    $(".datepicker").datepicker({
        dateFormat : "yy-mm-dd",
        yearRange: "-100:+5",
        changeMonth: true,
        changeYear: true
    });

  });

   

app/views/collections/index/_export.haml
.greyback{style: 'display:inline-block; float:left; padding-top:6px;'}
  %span#export
    = t('views.collections.index.export_this_result_in')
    %span.link{ko(click: '$root.exportInRSS')} RSS
    = t('views.collections.index.comma')
    %span.link{ko(click: '$root.exportInJSON')} JSON
    = t('views.collections.index.comma')
    %span.link{ko(click: '$root.exportInKML')} KML
    = t('views.collections.index.comma')
    %span.link{ko(click: '$root.exportInCSV')} CSV
    = t('views.collections.index.or')
    %span.link{ko(click: '$root.exportInSHP')} SHP

app/views/collections/index/_field_hierarchy_items_template.haml
-# Field hierarchy item template (used when selecting a hierarchy field value for a site)
%script{type: "text/html", id: "field-hierarchy-items-template"}
  <!-- ko foreach: fieldHierarchyItems -->
  .hierarchy{ko(css: {active: 'selected()'})}
    %a{ko(style: {marginLeft: "'' + (level * 20) + 'px'"}), href: 'javascript:void(0)'}
      <!-- ko if: id != '' -->
      %img{ko(click: :toggleExpand, attr: {src: "'#{InsteddRails.url}/theme/images/icons/18/black/folder' + (expanded() ? '_open' : '') + '.png'"}), style: 'position:relative;top:2px'}
      <!-- /ko -->
      %span{ko(click: :select, text: :name)}
  <!-- ko if: expanded -->
  <!-- ko template: {name: 'field-hierarchy-items-template', with: fieldHierarchyItems} -->
  <!-- /ko -->
  <!-- /ko -->
  <!-- /ko -->

app/views/collections/index/_map_hierarchy_items_template.haml
-# Hierarchy item template (used when grouping results by hierarchy item)
%script{type: "text/html", id: "map-hierarchy-items-template"}
  <!-- ko foreach: hierarchyItems -->
  %tr
    %td.hierarchyItem{ko(click: :toggleExpand, style: :columnStyle)}
      %div{ko(style: :labelStyle, css: {greyback: :isSelected})}
        %a{href: 'javascript:void(0)'}
          %img{ko(attr: {src: "'#{InsteddRails.url}/theme/images/icons/18/black/folder' + (expanded() ? '_open' : '') + '.png'"})}
        %span{ko(text: :name)}
  <!-- ko if: expanded -->
  <!-- ko template: {name: 'map-hierarchy-items-template', with: hierarchyItems} -->
  <!-- /ko -->
  <!-- ko template: {name: 'map-sites-template', with: $data} -->
  <!-- /ko -->
  <!-- ko if: hasMoreSites() && !loadingSites()-->
  %tr
    %td.loadmore
      = link_to t('views.collections.index.load_more_sites'), 'javascript:void()', 'data-bind' => kov(click: :loadMoreSites, style: {marginLeft: "'' + (30 + level * 20) + 'px'"})
  <!-- /ko -->
  <!-- ko if: hasMoreSites() && loadingSites()-->
  %tr
    %td.loadmore
      %span{ko(style: {marginLeft: "'' + (30 + (level + 1) * 20) + 'px'"})}= t('views.collections.index.loading')
  <!-- /ko -->
  <!-- /ko -->
  <!-- /ko -->

app/views/collections/index/_map_hierarchy_sites_template.haml
%script{type: "text/html", id: "map-hierarchy-sites-template"}
  <!-- ko foreach: hierarchySites -->
  %tr
    %td
      %div.hierarchyItem{ko(click: :selectedHierarchy, style: :columnStyle)}
        %div{ko(style: :labelStyle, css: {greyback: :selected})}
          %a{href: 'javascript:void(0)'}
            %img{ko(attr: {src: "'#{InsteddRails.url}/theme/images/icons/18/black/folder' + (expanded() ? '_open' : '') + '.png'"})}
          %span{ko(text: :name)}
      %button.farrow{ko(click: '$root.editSiteInHierarchyMode'), type: "button"}
  <!-- ko if: expanded -->
  <!-- ko template: {name: 'map-hierarchy-sites-template', with: hierarchySites} -->
  <!-- /ko -->
  <!-- /ko -->
  <!-- /ko -->

app/views/collections/index/_map_sites_template.haml
-# Sites template
%script{type: "text/html", id: "map-sites-template"}
  <!-- ko foreach: sites -->
  %tr
    %td
      %div{ko(style: {width: "'' + (272 - ($parent.level + 1) * 20 - 30) + 'px'", marginLeft: "'' + (($parent.level + 1) * 20 + 6) + 'px'"}, css: {greyback: "$data == $root.selectedSite()"}), style: 'padding-left:2px;margin-top:5px;margin-left:8px;width:220px;'}
        %p{ko(click: '$root.selectSite'), style: 'cursor: pointer'}
          %span.stat-r
          %span{ko(html: :highlightedName)}
      %button.farrow{ko(click: '$root.editSite'), type: "button"}
  <!-- /ko -->

app/views/collections/index/_refine_hierarchy_items_template.haml
-# Refine hierarchy item template (used when selecting a hierarchy field value as refine field)
%script{type: "text/html", id: "refine-hierarchy-items-template"}
  <!-- ko foreach: fieldHierarchyItems -->
  .hierarchy{ko(css: {active: 'selected()'})}
    %a{ko(style: {marginLeft: "'' + (level * 20) + 'px'"}), href: 'javascript:void(0)'}
      <!-- ko if: id != '' -->
      %img{ko(click: :toggleExpand, attr: {src: "'#{InsteddRails.url}/theme/images/icons/18/black/folder' + (expanded() ? '_open' : '') + '.png'"}), style: 'position:relative;top:2px'}
      <!-- /ko -->
      %span{ko(click: '$root.expandedRefinePropertyHierarchy', text: :name)}
  <!-- ko if: expanded -->
  <!-- ko template: {name: 'refine-hierarchy-items-template', with: fieldHierarchyItems} -->
  <!-- /ko -->
  <!-- /ko -->
  <!-- /ko -->

app/views/collections/index/_table_hierarchy_items_template.haml
-# Hierarchy item template (used when grouping results by hierarchy item)
%script{type: "text/html", id: "table-hierarchy-items-template"}
  <!-- ko foreach: hierarchyItems -->
  %tr
    %td.w30{ko(click: :toggleExpand), style: 'overflow:auto;height:30px;cursor:pointer'}
      %div{style: 'margin-top:5px'}
        %a{ko(style: {marginLeft: "'' + (level * 20) + 'px'"}), href: 'javascript:void(0)'}
          %img{ko(attr: {src: "'#{InsteddRails.url}/theme/images/icons/18/black/folder' + (expanded() ? '_open' : '') + '.png'"})}
        %span{ko(text: :name)}
    <!-- ko foreach: $root.currentCollection().fields() -->
    %td.l
    <!-- /ko -->
    %td.l
    %td.l
  <!-- ko if: expanded -->
  <!-- ko template: {name: 'table-hierarchy-items-template', with: hierarchyItems} -->
  <!-- /ko -->
  <!-- ko template: {name: 'table-sites-template', with: $data} -->
  <!-- /ko -->
  <!-- ko if: hasMoreSites() && !loadingSites()-->
  %tr
    %td.loadmore
      = link_to t('views.collections.index.load_more_sites'), 'javascript:void()', 'data-bind' => kov(click: :loadMoreSites, style: {marginLeft: "'' + (30 + level * 20) + 'px'"})
  <!-- /ko -->
  <!-- ko if: hasMoreSites() && loadingSites()-->
  %tr
    %td.loadmore
      %span{ko(style: {marginLeft: "'' + (30 + (level + 1) * 20) + 'px'"})}= t('views.collections.index.loading')
  <!-- /ko -->
  <!-- /ko -->

app/views/collections/index/_table_sites_template.haml
-# Sites template
%script{type: "text/html", id: "table-sites-template"}
  <!-- ko foreach: partlySites -->
  %tr
    %td{style: 'overflow:auto'}
      %div{style: 'margin-top:5px'}
        %p{ko(style: {marginLeft: "'' + (($parent.level + 1) * 20) + 'px'"}, click: '$root.selectSite'), style: 'cursor: pointer'}
          %span.stat-r
          %span{ko(html: :highlightedName)}
      %button.farrow{ko(click: '$root.editSite'), type: :button}
    /ko if: collection.isVisibleLocation
    %td.padded
      %span{ko(text: :safe_lat)}
    %td.padded
      %span{ko(text: :safe_lng)}
    //ko
    %td.padded
      %span{ko(text: :week)}
    %td.padded
      %span{ko(text: :year)}
    %td.padded
      %span{ko(text: :place_name)}
    <!-- ko foreach: $root.currentCollection().fields() -->
    %td.padded
      <!-- ko if: kind == 'photo' -->
      <!-- ko if: $parent.propertyValue($data) -->
      %img{ko(attr: {src: "photoPath + $parent.propertyValue($data)"}), width: "36px"}
      <!-- /ko -->
      <!-- /ko -->
      <!-- ko if: kind != 'photo' -->
      %span{ko(attr: "{ title: $parent.highlightedPropertyValue($data) }", text: "$parent.highlightedPropertyValue($data)"), style: 'vertical-align:top'}
      <!-- /ko -->
    <!-- /ko -->
    %td.timeago.padded{ko(attr: "{title: updatedAt}", text: :updatedAtTimeago)}
    %td.padded
  <!-- /ko -->