config/routes.rb
ResourceMap::Application.routes.draw do

  # devise_for :users, :controllers => {:registrations => "registrations", :sessions => 'sessions' }
  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: "omniauth_callbacks"}
  guisso_for :user

  # match 'messaging' => 'messaging#index'
  match 'nuntium' => 'nuntium#receive', :via => :post
  match 'authenticate' => 'nuntium#authenticate', :via => :post
  match 'android/collections' => 'android#collections_json', :via => :get
  match 'android/submission' => 'android#submission', :via => :post
  match 'collections/breadcrumbs' => 'collections#render_breadcrumbs', :via => :post
  match 'real-time-resource-tracking' => 'home#second_page', :via => :get
  match 'track-medical-supplies-and-personnel'=> 'home#medical_page', :via => :get
  match 'track-food-prices-and-supplies' => 'home#food_page', :via => :get
  match 'collections/alerted-collections' => 'collections#alerted_collections', :via => :get
  #match 'analytics' => 'analytics#index', :via => :get
  get 'download/activity' => "activities#download"
  match 'get_user_auth_token' => "application#get_user_auth_token", :via => 'get'
  match 'load_app_cache' => 'home#load_app_cache', :via => 'get'
  get 'plugin/alerts/thresholds' => 'thresholds#index'
  get 'channels_accesses/search_user'
  get 'channels_accesses/search_collection'

  resources :repeats
  resources :collections do
    post  :send_new_member_sms
    post :register_gateways
    get  :message_quota
    get :sites_by_term
    resources :sites do
      get :visible_layers_for
    end
    resources :layers do

      member do
        put :set_order
      end

      collection do
        post :upload_layers
        get :adjust_layers
        get :pending_layers
      end
    end
    resources :fields

    resources :memberships do
      collection do
        get 'invitable'
        get 'search'
      end
      member do
        post 'set_layer_access'
        post 'set_admin'
        post 'unset_admin'
      end
    end
    resources :sites_permission

    resources :reports do
      collection do
        get 'download'
        get 'report'
        get 'get_monthly_graph'
        get 'monthly_graph'
        get 'weekly_graph'
        get 'get_weekly_graph'
      end
    end
    resources :places do
      get 'all'
      collection do
        post 'create_memberships'
        post 'create_hierarchy'
        put 'update_hierarchy'
        delete 'delete_membership'
        get 'memberships'
        get 'download_template'
        get 'download'
        get 'my_supervision_place'
        resource :import_hierarchy_wizard, only: [] do
           get 'index'
           post 'upload_xls'
           get 'adjustments'
           get 'guess_columns_spec'
           post 'execute'
           post 'validate_sites_with_columns'
           get 'get_visible_sites/:page' => 'import_wizards#get_visible_sites'
           get 'import_in_progress'
           get 'import_finished'
           get 'import_failed'
           get 'job_status'
           get 'cancel_pending_jobs'
           get 'logs'
           get 'places'
           get 'memberships'
        end
      end
    end

    get 'members'
    get 'settings'
    get 'quotas'
    get 'csv_template'
    get 'max_value_of_property'

    post 'upload_csv'

    post 'create_snapshot'
    post 'load_snapshot'
    post 'unload_current_snapshot'

    get 'recreate_index'
    get 'search'
    post 'decode_hierarchy_csv'
    post 'decode_location_csv'

    get 'sites_info'

    resource :import_wizard, only: [] do
       get 'index'
       post 'upload_csv'
       get 'adjustments'
       get 'guess_columns_spec'
       post 'execute'
       post 'validate_sites_with_columns'
       get 'get_visible_sites/:page' => 'import_wizards#get_visible_sites'
       get 'import_in_progress'
       get 'import_finished'
       get 'import_failed'
       get 'job_status'
       get 'cancel_pending_jobs'
       get 'logs'
    end
  end

  resources :sites do
    get 'root_sites'
    get 'search', :on => :collection
    get 'search_alert_site', :on => :collection

    post 'update_property'
  end

  resources :messages, :only => [:index], :path => 'message'
  resources :activities, :only => [:index], :path => 'activity'
  resources :quotas
  resources :channels_accesses

  resources :gateways do
    post 'status', :on => :member
    post 'try'
  end

  match 'terms_and_conditions' => redirect("http://instedd.org/terms-of-service/"), :via => :get

  namespace :api do
    get 'collections/:id' => 'collections#show',as: :collection
    get 'collections/:id/export_layers' => 'collections#export_layers', as: :export_layers
    get 'collections/:id/download_location_csv' => 'collections#download_location_csv', as: :download_location_csv
    get 'collections/:id/sample_csv' => 'collections#sample_csv',as: :sample_csv
    get 'collections/:id/count' => 'collections#count',as: :count
    get 'collections/:id/geo' => 'collections#geo_json',as: :geojson
    get 'sites/:id' => 'sites#show', as: :site
    get 'activity' => 'activities#index', as: :activity
    # match 'collections/:id/update_sites_under_collection' => 'collections#update_sites_under_collection', :via => :put
    # put 'collections/:id/update_sites_under_collection' => 'collections#update_sites_under_collection', as: :collections
    resources :tokens, :only => [:index, :destroy]
    resources :collections do
      get 'sites_by_term'
      member do
        put 'update_sites'
        get 'get_fields'
        get 'get_sites_conflict'
        get 'get_some_sites'
      end
      resources :fields, only: [:index]
      resources :sites
    end
    match 'collections/:collection_id/memberships' => 'memberships#create', :via => :post
    match 'collections/:collection_id/memberships' => 'memberships#update', :via => :put
    match 'collections/:collection_id/register_new_member' => 'memberships#register_new_member', :via => :post
    match 'collections/:collection_id/destroy_member' => 'memberships#destroy_member', :via => :delete

    devise_scope :user do
      post '/users' => 'registrations#create'
      post '/users/sign_in' => 'sessions#create'
      post '/users/sign_out' => 'sessions#destroy'
    end

    # v1
    namespace :v1 do
      resources :collections do
        resources :sites, only: [:create,:index,:update, :show] do
          get :visible_layers_for, on: :member
          collection do
            get 'get_site_by_week_year_place'
          end
        end
        resources :memberships, only: [:index] do
          collection do
            get 'search'
          end
        end
        resources :fields, only: [:create,:index,:update,:show]
        resources :layer_memberships, only: [:create,:index,:update,:show]
        resources :site_permissions, only: [:create,:index,:update,:show]
        resources :places do
          collection do
            get 'my_supervision_place'
            get 'get_parent_place_by_ancestry_id'
            get 'memberships'
          end
        end
      end
      namespace :admin do
        resources :collections
      end
    end

    # v2
    namespace :v2 do
      resources :collections, except: [:update] do
        resources :memberships, only: [:index, :create, :destroy] do
          member do
            post :set_admin
            post :unset_admin
          end
          collection do
            get 'invitable'
          end
        end

        resources :layers, except: [:show, :new, :edit] do
          resources :fields, only: [:create]
        end

        resources :fields, only: [:index] do
          collection do
            get 'mapping'
          end
        end

        member do
          get 'sample_csv', as: :sample_csv
          get 'count', as: :count
          get 'geo', as: :geojson, to: "collections#geo_json"
          post 'sites', to: 'sites#create'
          post 'update_sites', to: 'collections#bulk_update'
        end
      end

      resources :sites, only: [:show, :destroy, :update] do
        member do
          post :update_property
          post :partial_update
        end
      end
      get 'histogram/:field_id', to: 'collections#histogram_by_field', as: :histogram_by_field
      get 'collections/:collection_id/sites/:id/histories' => 'sites#histories', as: :histories
      get 'activity' => 'activities#index', as: :activity
      resources :tokens, :only => [:index, :destroy]
    end
  end

  namespace :mobile do
    resources :collections do
      resources :sites do
        get :visible_layers_for, on: :member
      end
      resources :sites_permission
      match 'create_offline_site' => 'sites#create_offline_site', :via => :post
    end
    match 'collections/:collection_id/sites/:id/update_offline_site' => 'sites#update_offline_site', :via => :put
  end

  scope '/plugin' do
    Plugin.all.each do |plugin|
      scope plugin.name do
        plugin.hooks[:routes].each { |plugin_routes_block| instance_eval &plugin_routes_block }
      end
    end
  end

  root :to => 'home#index'

  admin_constraint = lambda do |request|
    request.env['warden'].authenticate? and request.env['warden'].user.is_super_user?
  end

  constraints admin_constraint do
    mount Resque::Server, :at => "/admin/resque"
    match 'analytics' => 'analytics#index', :via => :get
    match 'quota' => 'quota#index', via: :get
  end

  offline = Rack::Offline.configure do
    cache "assets/mobile.js"
    cache "assets/mobile.css"

    cache "assets/jquery.mobile-1.3.2.js"
    cache "assets/jquery.mobile-1.3.2.css"

    cache "assets/images/ajax-loader.gif"
    cache "assets/images/icons-18-white.png"
    cache "assets/images/icons-36-white.png"

    cache "images/add.png"
    cache "images/remove.ico"
    cache "images/favicon.ico"
    network "*"
  end
  match "/application.manifest" => offline, :via => :get

  # TODO: deprecate later

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_filter :setup_guest_user, :if => Proc.new { collection }
  before_filter :authenticate_user!
  before_filter :authenticate_collection_admin!, :only => [:download, :index]
  # authorize_resource :except => [:render_breadcrumbs], :decent_exposure => true, :id_param => :collection_id

  def index
    @places = Place.to_hierachy(collection)
    @fields = collection.fields.select([:name, :id, :kind]).to_json
    respond_to do |format|
      format.html do
        show_collection_breadcrumb
        add_breadcrumb I18n.t('views.collections.index.properties'), collection_path(collection)
        add_breadcrumb I18n.t('views.collections.tab.health_structure'), collection_places_path(collection)
      end
      format.json { render json:  @places, :root => false}
    end  
  end

  # def download
  #   ods = Place.find_all_by_kind_of("OD")
  #   from_week = params[:fromWeek]
  #   from_year = params[:fromYear]
  #   to_week = params[:toWeek]
  #   to_year = params[:toYear]
  #   from = from_year.to_i * 52 + from_week.to_i
  #   to = to_year.to_i * 52 + to_week.to_i
  #   @data = {}
  #   @total = {}
  #   ods.each do |od|
  #     sites = od.get_sites(current_user, from, to)
  #     @data.merge!(sites)
  #     sites.each do |key, value|
  #       @total.merge!(value) {|key,val1,val2| val1.to_i + val2.to_i}
  #     end
  #   end
  #   fields = collection.fields.in_groups(2)
  #   @fields_first = fields[0]
  #   @fields_second = fields[1]
  #   render pdf: "report_#{from_week}_#{from_year}_to#{to_week}_#{to_year}.pdf", :layout => false, orientation: 'Landscape'
  # end

  def report
    ods = Place.find_all_by_kind_of("OD")
    calculation_fields = collection.fields.find_all_by_kind("calculation")
    @field_ids = params["field_ids"]
    @from_week = params[:fromWeek]
    @from_year = params[:fromYear]
    @to_week = params[:toWeek]
    @to_year = params[:toYear]
    from = @from_year.to_i * 52 + @from_week.to_i
    to = @to_year.to_i * 52 + @to_week.to_i
    @data = {}
    @data_village = {}
    @total = {}
    @total_village = {}
    ods.each do |od|
      @data_village = {}
      @total_village = {}
      villages = od.children
      villages.each do |v|
        sites = v.get_sites(current_user, from, to)
        @data_village.merge!(sites)
        sites.each do |key, value|
          @total_village.merge!(value) {|key,val1,val2| val1.to_i + val2.to_i}
        end

        calculation_fields.each do |field|
          field.config["dependent_fields"].each do |key, df|
            field.config["code_calculation"].gsub!("${#{df['code']}}", '"' +  @total_village["#{df['id']}"].to_s + '"' + ".to_f")
          end
          p field.config["code_calculation"]
          @total_village[field.id.to_s] = eval(field.config["code_calculation"]).round(2)
          @total_village[field.id.to_s] = 0 if @total_village[field.id.to_s].nan?
        end
      end
      @total.merge!({"#{od.id}" => @total_village})
      @data.merge!({"#{od.id}" => @data_village})

    end
    @fields = collection.fields.where("id IN (?)",@field_ids)

    # render :layout => false
    render pdf: "report_#{@from_week}_#{@from_year}_to_#{@to_week}_#{@to_year}.pdf", :layout => false
  end

  def monthly_graph
    @from_month = params[:fromMonth]
    @from_year = params[:fromYear]
    @to_month = params[:toMonth]
    @to_year = params[:toYear]
    @field_id = params[:field_id]
    # render pdf: "report.pdf", :layout => false
    render :layout => false
  end

  def get_monthly_graph
    #TODO Replace with selected year
    column = collection.places.find_all_by_kind_of("OD").map(&:name)
    districts = collection.places.find_all_by_kind_of("OD")
    from_month = params[:from_month]
    from_year = params[:from_year]
    to_month = params[:to_month]
    to_year = params[:to_year]
    field_id = params[:field_id]
    diff = (to_year.to_i - from_year.to_i).abs * 12 + (to_month.to_i - from_month.to_i).abs + 1

    now = DateTime.now()
    from_date = now.change(:year => from_year.to_i, :month => from_month.to_i.to_i)
    to_date = now.change(:year => to_year.to_i, :month => to_month.to_i)
    if from_date < to_date
      base_date = from_date.beginning_of_month 
    else
      base_date = to_date.beginning_of_month 
    end
    data = []
    tmp = []
    (1..diff).each do |m|
      tmp = [m]
      districts.each do |d|
        from_date = base_date
        to_date = from_date.at_end_of_month
        sites = d.get_site_by_date(current_user, from_date, to_date)
        #Replace with Field id
        if sites[field_id]
          tmp.push(sites[field_id])
        else
          tmp.push(0)
        end
      end
      base_date = base_date.next_month
      data.push(tmp)
    end
    render :json => {:column => column, :data => data}.to_json, :root => false, :head => :ok
  end

  def weekly_graph
    @from_week = params[:fromWeek]
    @from_year = params[:fromYear]
    @to_week = params[:toWeek]
    @to_year = params[:toYear]
    @field_id = params[:field_id]
    # render pdf: "report.pdf", :layout => false
    render :layout => false
  end

  def get_weekly_graph
    #TODO Replace with selected year
    column = collection.places.find_all_by_kind_of("OD").map(&:name)
    districts = collection.places.find_all_by_kind_of("OD")
    from_week = params[:from_week]
    from_year = params[:from_year]
    to_week = params[:to_week]
    to_year = params[:to_year]
    from = from_year.to_i * 52 + from_week.to_i
    to = to_year.to_i * 52 + to_week.to_i
    field_id = params[:field_id]
    diff = (to - from).abs + 1
    if from < to
      base_week = from
    else
      base_week = to
    end
    data = []
    tmp = []
    (1..diff).each do |m|
      tmp = [m]
      districts.each do |d|
        sites = d.get_sites(current_user, base_week, base_week)
        #Replace with Field id
        if sites[d.id.to_s][field_id]
          tmp.push(sites[d.id.to_s][field_id])
        else
          tmp.push(0)
        end
      end
      base_week = base_week + 1
      data.push(tmp)
    end
    render :json => {:column => column, :data => data}.to_json, :root => false, :head => :ok
  end

end

app/views/reports/download.html.erb
<html lang = "en" >
  <head>
    <meta http-equiv='content-type' content='text/html; charset=utf-8' /> 
    <title>Resource Map</title>
    <script src="/assets/application.js"></script>
    <link href="http://theme.instedd.org/theme/stylesheets/theme.css" rel="stylesheet" />
    <script src="http://theme.instedd.org/theme/javascripts/theme.js"></script>
    <link href="/assets/application.css" media="screen" rel="stylesheet" />
  </head>
  <body style="background: none;">
    <div style="width:100%;">
      <p>
        <center>
          <h2>This is the first center header</h2>
        </center>
      </p>
      <p>
        <center>
          <h3>This is the first center header</h3>
        </center>
      </p>
      <p>
        <h3>Helllo one</h3>
      </p>
      <p> 
        <h3>Hello two<h3>
      </p>
      <center>
        <h3>This is the report from xxx to zzz for CMPE to edit<h3>
      </center>
    </div>
    <br/>
    <div class="fht-table-wrapper GralTable" >
      <div class="fht-tbody">
        <table style="table-layout: fixed; width: 1200px; margin-top: 0px;" class="GralTable tableview fht-table fht-table-init">
          </colgroup>
          <thead>
            <tr>
              <th style="width:50px;">
                <span style="display:inline">#</span>
              </th>
              <th style="width:150px;">
                <span style="display:inline">District</span>
              </th>
              <% @fields_first.each do |field| %>
                <th style="width:150px;">
                  <span style="display:inline"><%= field[:name] %></span>
                </th>
              <% end %>
              <th style="padding-right: 6px;">
                <div class="fht-cell" style="width: 0px;">
                </div>
              </th>
            </tr>
          </thead>
          <tbody>
            <tr></tr>
            <% i = 1 %>
            <% @data.each do |key, row| %>
              <tr>
                <td style="overflow:auto">
                  <div style="margin-top:5px">
                    <p style="cursor: pointer">
                      <span><%= i %></span>
                    </p>
                    <% i = i + 1 %>
                  </div>
                </td>
                <td style="overflow:auto">
                  <div style="margin-top:5px">
                    <p style="cursor: pointer">
                      <span><%= Place.find(key).name %></span>
                    </p>
                  </div>
                </td>
                <% @fields_first.each do |field| %>
                    <td style="overflow:auto">
                      <div style="margin-top:5px">
                        <p style="cursor: pointer">
                          <span><%= row[field[:id].to_s] || "" %></span>
                        </p>
                      </div>
                    </td>
                <% end %>
                <td class="padded" style=""></td>
              </tr>
            <% end %>
            <tr>
              <td style="overflow:auto">
                <div style="margin-top:5px">
                  <p style="cursor: pointer">
                    <span></span>
                  </p>
                  <% i = i + 1 %>
                </div>
              </td>
              <td style="overflow:auto">
                <div style="margin-top:5px">
                  <p style="cursor: pointer">
                    <span>Total</span>
                  </p>
                </div>
              </td>
              <% @fields_first.each do |field| %>
                  <td style="overflow:auto">
                    <div style="margin-top:5px">
                      <p style="cursor: pointer; color: red;">
                        <span><%= @total[field[:id].to_s] || "" %></span>
                      </p>
                    </div>
                  </td>
              <% end %>
              <td class="padded" style=""></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <br/>
    <br/>
    <div class="fht-table-wrapper GralTable">
      <div class="fht-tbody">
        <table style="table-layout: fixed; width: 1200px; margin-top: 0px;" class="GralTable tableview fht-table fht-table-init">
          </colgroup>
          <thead>
            <tr>
              <th style="width:50px;">
                <span style="display:inline">#</span>
              </th>
              <th style="width:150px;">
                <span style="display:inline">District</span>
              </th>
              <% @fields_second.each do |field| %>
                <% unless field.nil? %> 
                  <th style="width:150px;">
                    <span style="display:inline"><%= field[:name] %></span>
                  </th>
                <% end %>
              <% end %>
              <th style="padding-right: 6px;">
                <div class="fht-cell" style="width: 0px;">
                </div>
              </th>
            </tr>
          </thead>
          <tbody>
            <tr></tr>
            <% i = 1 %>
            <% @data.each do |key, row| %>
              <tr>
                <td style="overflow:auto">
                  <div style="margin-top:5px">
                    <p style="cursor: pointer">
                      <span><%= i %></span>
                    </p>
                    <% i = i + 1 %>
                  </div>
                </td>
                <td style="overflow:auto">
                  <div style="margin-top:5px">
                    <p style="cursor: pointer">
                      <span><%= Place.find(key).name %></span>
                    </p>
                  </div>
                </td>
                <% @fields_second.each do |field| %>
                  <% unless field.nil? %> 
                    <td style="overflow:auto">
                      <div style="margin-top:5px">
                        <p style="cursor: pointer">
                          <span><%= row[field[:id].to_s] || "" %></span>
                        </p>
                      </div>
                    </td>
                  <% end %>
                <% end %>
                <td class="padded" style=""></td>
              </tr>
            <% end %>
            <tr>
              <td style="overflow:auto">
                <div style="margin-top:5px">
                  <p style="cursor: pointer">
                    <span></span>
                  </p>
                  <% i = i + 1 %>
                </div>
              </td>
              <td style="overflow:auto">
                <div style="margin-top:5px">
                  <p style="cursor: pointer">
                    <span>Total</span>
                  </p>
                </div>
              </td>
              <% @fields_second.each do |field| %>
                <% unless field.nil? %> 
                  <td style="overflow:auto">
                    <div style="margin-top:5px">
                      <p style="cursor: pointer; color: red;">
                        <span><%= @total[field[:id].to_s] || "" %></span>
                      </p>
                    </div>
                  </td>
                <% end %>
              <% end %>
              <td class="padded" style=""></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </body>
</html>

app/views/reports/index.haml
= render '/tabs'

- content_for :head do
  :javascript
    $(function() { initReports(#{collection.id}, #{@fields})});
  :css
    table.GralTable td.center { text-align: center; }

.tabsline
  #reports-main
    %h2= t('views.reports.title')
    %p= t('views.reports.description')

    %label= t('views.reports.from_week')
    %select{ko(options: 'listWeek', value: :fromWeek)}
    %label= t('views.reports.of_the_year')
    %select{ko(options: 'listYear', value: :fromYear)}
    %label= t('views.reports.to_week')
    %select{ko(options: 'listWeek', value: :toWeek)}
    %label= t('views.reports.of_the_year')
    %select{ko(options: 'listYear', value: :toYear)}
    %br/
    %label= t('views.reports.field')
    %br/
    <!-- ko foreach: fields -->
    %input.collection_id{ko(value: "id", click: "$root.selectField", checked: 'checked'), type: 'checkbox'}
    %label{ko(text: 'name')}
    %br/
    <!-- /ko -->
    .clear
    %br/
    %button.csvDownload.white.left{ko(click: 'generateReport')}
      = t('views.reports.generate_report')
  %br
  %br
  %br
  %hr.clear/
  %br 
  #places-main
    %h2= t('views.reports.monthly_graph')
    %p= t('views.reports.generate_monthly_hi_ci_bi_graph')

    %label= t('views.reports.from_month')
    %select{ko(options: 'listMonth', value: :fromMonthlyReportWeek)}
    %label= t('views.reports.of_the_year')
    %select{ko(options: 'listYear', value: :fromMonthlyReportYear)}
    %label= t('views.reports.to_month')
    %select{ko(options: 'listMonth', value: :toMonthlyReportWeek)}
    %label= t('views.reports.of_the_year')
    %select{ko(options: 'listYear', value: :toMonthlyReportYear)}
    %br/
    %br/
    %label= t('views.reports.field')
    %select.w25{ko(value: :selectedField, options: :listAvailableField, optionsText: 'function(o){return labelFor(o)}', hasfocus: true)}
    .clear
    %br
    %button.csvDownload.white.left{ko(click: 'generateMonthlyGraph')}
      = t('views.report.generate_graph_report')
    %br
  %br
  %br
  %br
  %hr.clear/
  #places-main
    %h2= t('views.reports.weekly_graph')
    %p= t('views.reports.generate_monthly_hi_ci_bi_graph')

    %label= t('views.reports.from_week')
    %select{ko(options: 'listWeek', value: :fromWeeklyReportWeek)}
    %label= t('views.reports.of_the_year')
    %select{ko(options: 'listYear', value: :fromWeeklyReportYear)}
    %label= t('views.reports.to_week')
    %select{ko(options: 'listWeek', value: :toWeeklyReportWeek)}
    %label= t('views.reports.of_the_year')
    %select{ko(options: 'listYear', value: :toWeeklyReportYear)}
    %br/
    %br/
    %label= t('views.reports.field')
    %select.w25{ko(value: :selectedWeeklyField, options: :listAvailableField, optionsText: 'function(o){return labelFor(o)}', hasfocus: true)}
    .clear
    %br
    %button.csvDownload.white.left{ko(click: 'generateWeeklyGraph')}
      = t('views.report.generate_graph_report')

app/views/reports/monthly_graph.html.erb
<html lang="en">
  <head>
    <meta http-equiv='content-type' content='text/html; charset=utf-8' /> 
    <title>Resource Map</title>
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <link href="http://theme.instedd.org/theme/stylesheets/theme.css" rel="stylesheet" />
    <script src="http://theme.instedd.org/theme/javascripts/theme.js"></script>
    <link href="/assets/application.css" media="screen" rel="stylesheet" />
    <script src="http://www.google.com/uds/modules/gviz/gviz-api.js"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

  </head>
  <script>
    google.charts.load('current', {'packages':['line']});
    google.charts.setOnLoadCallback(drawChart);

    function drawChart() {

      $.ajax({
        url: "<%= get_monthly_graph_collection_reports_path() %>",
        type: "GET",
        data: {
                "field_id": "<%= @field_id %>", 
                "from_month" : "<%= @from_month %>",
                "from_year": "<%= @from_year %>",
                "to_month": "<%= @to_month %>",
                "to_year": "<%= @to_year %>"
        },
        success: function(response){
          var data = new google.visualization.DataTable();
          console.log(response);
          data.addColumn('number', 'ເດືອນ');
          for(var i=0; i< response["column"].length; i++){
            data.addColumn('number', response["column"][i]);
          }

          list = response["data"]

          data.addRows(list);
          var options = {
            chart: {
              title: 'ການເຝິາລະວ້ງຄວາມໜາແໜ້ນໜອນນຳຍຸງລາຍ ປະຈຳເດຶອນ',
              subtitle: "ແຕ່ເດືອນ <%= @from_week %>/<%= @from_year %> - <%= @to_week %>/<%= @to_year %> "
            },
            width: 900,
            height: 500
          };
          var chart = new google.charts.Line(document.getElementById('linechart_material'));
          chart.draw(data, options);
        },
        dataType: "json"
      });
    }
  </script>
  <body style="background: none;">
    <br />
    <br />
    <center>
      <div id="linechart_material">

      </div>

    </center>
  </body>
</html>

app/views/reports/weekly_graph.html.erb
<html lang="en">
  <head>
    <meta http-equiv='content-type' content='text/html; charset=utf-8' /> 
    <title>Resource Map</title>
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <link href="http://theme.instedd.org/theme/stylesheets/theme.css" rel="stylesheet" />
    <script src="http://theme.instedd.org/theme/javascripts/theme.js"></script>
    <link href="/assets/application.css" media="screen" rel="stylesheet" />
    <script src="http://www.google.com/uds/modules/gviz/gviz-api.js"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

  </head>
  <script>
    google.charts.load('current', {'packages':['bar']});
    google.charts.setOnLoadCallback(drawChart);

    function drawChart() {

      $.ajax({
        url: "<%= get_weekly_graph_collection_reports_path() %>",
        type: "GET",
        data: {
                "field_id": "<%= @field_id %>", 
                "from_week" : "<%= @from_week %>",
                "from_year": "<%= @from_year %>",
                "to_week": "<%= @to_week %>",
                "to_year": "<%= @to_year %>"
        },
        success: function(response){
          var data = new google.visualization.DataTable();
          console.log(response);
          data.addColumn('number', 'ອາທິດ');
          for(var i=0; i< response["column"].length; i++){
            response["column"][i][0] = "ອາທິດ " + response["column"][i][0]
            data.addColumn('number', response["column"][i]);
          }

          list = response["data"]

          data.addRows(list);
          var options = {
            chart: {
              title: 'ການເຝິາລະວ້ງຄວາມໜາແໜ້ນໜອນນຳຍຸງລາຍ ປະຈຳເດຶອນ',
              subtitle: "ແຕ່ເດືອນ <%= @from_month %>/<%= @from_year %> - <%= @to_month %>/<%= @to_year %> "
            }
          };

          var chart = new google.charts.Bar(document.getElementById('linechart_material'));
          chart.draw(data, options);
        },
        dataType: "json"
      });
    }
  </script>
  <body style="background: none;">
    <br />
    <br />
    <center>
      <div id="linechart_material" style="height:600px;width:80%;">

      </div>

    </center>
  </body>
</html>