config/routes.rb
ResourceMap::Application.routes.draw do

  # devise_for :users, :controllers => {:registrations => "registrations", :sessions => 'sessions' }
  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: "omniauth_callbacks"}
  guisso_for :user

  # match 'messaging' => 'messaging#index'
  match 'nuntium' => 'nuntium#receive', :via => :post
  match 'authenticate' => 'nuntium#authenticate', :via => :post
  match 'android/collections' => 'android#collections_json', :via => :get
  match 'android/submission' => 'android#submission', :via => :post
  match 'collections/breadcrumbs' => 'collections#render_breadcrumbs', :via => :post
  match 'real-time-resource-tracking' => 'home#second_page', :via => :get
  match 'track-medical-supplies-and-personnel'=> 'home#medical_page', :via => :get
  match 'track-food-prices-and-supplies' => 'home#food_page', :via => :get
  match 'collections/alerted-collections' => 'collections#alerted_collections', :via => :get
  #match 'analytics' => 'analytics#index', :via => :get
  get 'download/activity' => "activities#download"
  match 'get_user_auth_token' => "application#get_user_auth_token", :via => 'get'
  match 'load_app_cache' => 'home#load_app_cache', :via => 'get'
  get 'plugin/alerts/thresholds' => 'thresholds#index'
  get 'channels_accesses/search_user'
  get 'channels_accesses/search_collection'

  resources :repeats
  resources :collections do
    post  :send_new_member_sms
    post :register_gateways
    get  :message_quota
    get :sites_by_term
    resources :sites do
      get :visible_layers_for
    end
    resources :layers do

      member do
        put :set_order
      end

      collection do
        post :upload_layers
        get :adjust_layers
        get :pending_layers
      end
    end
    resources :fields

    resources :memberships do
      collection do
        get 'invitable'
        get 'search'
      end
      member do
        post 'set_layer_access'
        post 'set_admin'
        post 'unset_admin'
      end
    end
    resources :sites_permission

    resources :reports do
      collection do
        get 'download'
        get 'report'
        get 'get_monthly_graph'
        get 'monthly_graph'
        get 'weekly_graph'
        get 'get_weekly_graph'
      end
    end
    resources :places do
      get 'all'
      collection do
        post 'create_memberships'
        post 'create_hierarchy'
        put 'update_hierarchy'
        delete 'delete_membership'
        get 'memberships'
        get 'download_template'
        get 'download'
        get 'my_supervision_place'
        resource :import_hierarchy_wizard, only: [] do
           get 'index'
           post 'upload_xls'
           get 'adjustments'
           get 'guess_columns_spec'
           post 'execute'
           post 'validate_sites_with_columns'
           get 'get_visible_sites/:page' => 'import_wizards#get_visible_sites'
           get 'import_in_progress'
           get 'import_finished'
           get 'import_failed'
           get 'job_status'
           get 'cancel_pending_jobs'
           get 'logs'
           get 'places'
           get 'memberships'
        end
      end
    end

    get 'members'
    get 'settings'
    get 'quotas'
    get 'csv_template'
    get 'max_value_of_property'

    post 'upload_csv'

    post 'create_snapshot'
    post 'load_snapshot'
    post 'unload_current_snapshot'

    get 'recreate_index'
    get 'search'
    post 'decode_hierarchy_csv'
    post 'decode_location_csv'

    get 'sites_info'

    resource :import_wizard, only: [] do
       get 'index'
       post 'upload_csv'
       get 'adjustments'
       get 'guess_columns_spec'
       post 'execute'
       post 'validate_sites_with_columns'
       get 'get_visible_sites/:page' => 'import_wizards#get_visible_sites'
       get 'import_in_progress'
       get 'import_finished'
       get 'import_failed'
       get 'job_status'
       get 'cancel_pending_jobs'
       get 'logs'
    end
  end

  resources :sites do
    get 'root_sites'
    get 'search', :on => :collection
    get 'search_alert_site', :on => :collection

    post 'update_property'
  end

  resources :messages, :only => [:index], :path => 'message'
  resources :activities, :only => [:index], :path => 'activity'
  resources :quotas
  resources :channels_accesses

  resources :gateways do
    post 'status', :on => :member
    post 'try'
  end

  match 'terms_and_conditions' => redirect("http://instedd.org/terms-of-service/"), :via => :get

  namespace :api do
    get 'collections/:id' => 'collections#show',as: :collection
    get 'collections/:id/export_layers' => 'collections#export_layers', as: :export_layers
    get 'collections/:id/download_location_csv' => 'collections#download_location_csv', as: :download_location_csv
    get 'collections/:id/sample_csv' => 'collections#sample_csv',as: :sample_csv
    get 'collections/:id/count' => 'collections#count',as: :count
    get 'collections/:id/geo' => 'collections#geo_json',as: :geojson
    get 'sites/:id' => 'sites#show', as: :site
    get 'activity' => 'activities#index', as: :activity
    # match 'collections/:id/update_sites_under_collection' => 'collections#update_sites_under_collection', :via => :put
    # put 'collections/:id/update_sites_under_collection' => 'collections#update_sites_under_collection', as: :collections
    resources :tokens, :only => [:index, :destroy]
    resources :collections do
      get 'sites_by_term'
      member do
        put 'update_sites'
        get 'get_fields'
        get 'get_sites_conflict'
        get 'get_some_sites'
      end
      resources :fields, only: [:index]
      resources :sites
    end
    match 'collections/:collection_id/memberships' => 'memberships#create', :via => :post
    match 'collections/:collection_id/memberships' => 'memberships#update', :via => :put
    match 'collections/:collection_id/register_new_member' => 'memberships#register_new_member', :via => :post
    match 'collections/:collection_id/destroy_member' => 'memberships#destroy_member', :via => :delete

    devise_scope :user do
      post '/users' => 'registrations#create'
      post '/users/sign_in' => 'sessions#create'
      post '/users/sign_out' => 'sessions#destroy'
    end

    # v1
    namespace :v1 do
      resources :collections do
        resources :sites, only: [:create,:index,:update, :show] do
          get :visible_layers_for, on: :member
          collection do
            get 'get_site_by_week_year_place'
          end
        end
        resources :memberships, only: [:index] do
          collection do
            get 'search'
          end
        end
        resources :fields, only: [:create,:index,:update,:show]
        resources :layer_memberships, only: [:create,:index,:update,:show]
        resources :site_permissions, only: [:create,:index,:update,:show]
        resources :places do
          collection do
            get 'my_supervision_place'
            get 'get_parent_place_by_ancestry_id'
            get 'memberships'
          end
        end
      end
      namespace :admin do
        resources :collections
      end
    end

    # v2
    namespace :v2 do
      resources :collections, except: [:update] do
        resources :memberships, only: [:index, :create, :destroy] do
          member do
            post :set_admin
            post :unset_admin
          end
          collection do
            get 'invitable'
          end
        end

        resources :layers, except: [:show, :new, :edit] do
          resources :fields, only: [:create]
        end

        resources :fields, only: [:index] do
          collection do
            get 'mapping'
          end
        end

        member do
          get 'sample_csv', as: :sample_csv
          get 'count', as: :count
          get 'geo', as: :geojson, to: "collections#geo_json"
          post 'sites', to: 'sites#create'
          post 'update_sites', to: 'collections#bulk_update'
        end
      end

      resources :sites, only: [:show, :destroy, :update] do
        member do
          post :update_property
          post :partial_update
        end
      end
      get 'histogram/:field_id', to: 'collections#histogram_by_field', as: :histogram_by_field
      get 'collections/:collection_id/sites/:id/histories' => 'sites#histories', as: :histories
      get 'activity' => 'activities#index', as: :activity
      resources :tokens, :only => [:index, :destroy]
    end
  end

  namespace :mobile do
    resources :collections do
      resources :sites do
        get :visible_layers_for, on: :member
      end
      resources :sites_permission
      match 'create_offline_site' => 'sites#create_offline_site', :via => :post
    end
    match 'collections/:collection_id/sites/:id/update_offline_site' => 'sites#update_offline_site', :via => :put
  end

  scope '/plugin' do
    Plugin.all.each do |plugin|
      scope plugin.name do
        plugin.hooks[:routes].each { |plugin_routes_block| instance_eval &plugin_routes_block }
      end
    end
  end

  root :to => 'home#index'

  admin_constraint = lambda do |request|
    request.env['warden'].authenticate? and request.env['warden'].user.is_super_user?
  end

  constraints admin_constraint do
    mount Resque::Server, :at => "/admin/resque"
    match 'analytics' => 'analytics#index', :via => :get
    match 'quota' => 'quota#index', via: :get
  end

  offline = Rack::Offline.configure do
    cache "assets/mobile.js"
    cache "assets/mobile.css"

    cache "assets/jquery.mobile-1.3.2.js"
    cache "assets/jquery.mobile-1.3.2.css"

    cache "assets/images/ajax-loader.gif"
    cache "assets/images/icons-18-white.png"
    cache "assets/images/icons-36-white.png"

    cache "images/add.png"
    cache "images/remove.ico"
    cache "images/favicon.ico"
    network "*"
  end
  match "/application.manifest" => offline, :via => :get

  # TODO: deprecate later

app/controllers/api/v1/places_controller.rb
module Api::V1

  class PlacesController < ApplicationController
    include Concerns::CheckApiDocs
    before_filter :authenticate_api_user!
    skip_before_filter :verify_authenticity_token

    def my_supervision_place
      unless current_user.admins? collection
        place = HierarchyMembership.find_by_user_id(current_user.id).place
        render :json => place.children.to_json
      else
        render :json => collection.places.to_json
      end
    end

    def get_parent_place_by_ancestry_id
      if params[:ancestry]
        ancestry_id = params[:ancestry].split("/").last
        place = Place.find(ancestry_id)
        render :json => place.to_json
      else
        render :json => nil
      end
    end

    def memberships
      membership = nil
      if current_user
        layer_memberships = collection.layer_memberships.all.inject({}) do |hash, membership|
          (hash[membership.user_id] ||= []) << membership
          hash
        end
        members = collection.memberships.where("user_id" => current_user.id ).includes([:user, :read_sites_permission, :write_sites_permission])
        membership = members[0]
        user_display_name = User.generate_user_display_name membership.user
        if user_display_name == membership.user.phone_number
          user_phone_number = ""
        else
          user_phone_number = membership.user.phone_number
        end

        membership = {
          user_id: membership.user_id,
          user_display_name: user_display_name,
          user_phone_number: user_phone_number,
          admin: membership.admin?,
          layers: (layer_memberships[membership.user_id] || []).map{|x| {layer_id: x.layer_id, read: x.read?, write: x.write?, create: x.create?}},
          sites: {
            none: membership.none_sites_permission,
            read: membership.read_sites_permission,
            write: membership.write_sites_permission,
            create: membership.create_sites_permission
          }
        }
      end
      render json: membership, :root => false
    end
  end
end

app/views/places/_add_hierarchy.haml
%div{ko(visible: :showRegisterNewHierarchy), class: "box centered w40 rm-dialog", id: "frm_new_hierarchy", style: "margin-left: -180px; display: none; margin-top: -175px; box-shadow: 0 3px 11px -1px rgba(0, 0, 0, 0.3)" }
  %h2= t('views.places.create_new_hierarchy')
  %div{:style => "margin-left: 132px;"}
    %span{ko(text: :nameError), :style => "color: red"}
  = t('views.places.name')
  %input#nameHierarchy{ko(value: :name, valueUpdate: :afterkeydown), :name => "email", :style => "margin-left: 88px; width: 250px;", :type => "text"}
  %br
  %br
  %div{:style => "margin-left: 132px;"}
    %span{ko(text: :codeError), :style => "color: red"}
  = t('views.places.code')
  %input#codeHierarchy{ko(value: :code, valueUpdate: :afterkeydown), :name => "phone_number", :style => "margin-left: 92px; width: 250px;", :type => "text"}
  %br
  %br

  %div{ style: "margin-left: 130px;"}
    %button{ko(click: '$root.createHierarchy', css: {disabled: '$root.hasHierarachyError()'}), type: "button", value: "Save", class: "white", id: "btn_create_member" }= t('views.places.submit')
    
    %button{ko(click: '$root.hideRegisterHierarchy'), type: "button", value: "Cancel", class: "white", id: "btn_close_member" }= t('views.places.cancel')

app/views/places/_add_member.haml
%tr{:style => 'height:32px'}
  %td{:colspan => 6}
    #autocomplete_container{style: 'width: 410px; float:left; margin-top:3px; margin-left:5px; margin-right: 5px;'}
      = text_field_tag :member_email, '', :placeholder => t('views.collections.members.search_by_email')
    %button.cadd#add_member{ko(click: '$root.showRegisterMembership'), style:"float:left;"}= t('views.collections.members.add_member')

app/views/places/_add_non_existed_member.haml
%div{ko(visible: :showRegisterNewMember), class: "box centered w40 rm-dialog", id: "frm_new_member", style: "margin-left: -180px; display: none; margin-top: -175px; box-shadow: 0 3px 11px -1px rgba(0, 0, 0, 0.3)" }
  %h2= t('views.collections.members.create_new_member')
  %div{:style => "margin-left: 132px;"}
    %span{ko(text: :emailError), :style => "color: red"}
  = t('views.collections.members.email')
  %input{ko(value: :email, valueUpdate: :afterkeydown), :name => "email", :style => "margin-left: 88px; width: 250px;", :type => "text"}
  %br
  %br
  %div{:style => "margin-left: 130px;"}
    = t('views.collections.members.phone_number_note')
  %div{:style => "margin-left: 132px;"}
    %span{ko(text: :phoneError), :style => "color: red"}
  = t('views.collections.members.phone_number')
  %input{ko(value: :phoneNumber, valueUpdate: :afterkeydown), :name => "phone_number", :style => "margin-left: 30px; width: 250px;", :type => "text"}
  %br
  %br
  %div{:style => "margin-left: 130px;"}
    = t('views.collections.members.need_to_verify_phone_number')
  %div{:style => "margin-left: 130px;"}
    %button{ko(click: '$root.sentCodeMsg', css: {disabled: '$root.phoneNumberExist()'}), type: "button", value: "text", class: "white" }= t('views.collections.members.text_me')
    %input{ko(value: :smsCode, valueUpdate: :afterkeydown), :name => "text_verify", :type => "text"}
  %div{:style => "margin-left: 130px; width: 250px;"}
    %span{ko(html: :codeVerificationMsg)}
  %div{style: "margin-bottom: 5px;"}
    %a{ko(text: :noChannelMsg), :href => collection_channels_path(collection), :style => "margin-left: 130px; color: red; text-decoration: underline;"}
  %div{ style: "margin-left: 130px;"}
    %button{ko(click: '$root.createMembership', css: {disabled: '$root.hasError()'}), type: "button", value: "Save", class: "white", id: "btn_create_member" }= t('views.collections.members.submit')
    
    %button{ko(click: '$root.hideRegisterMembership'), type: "button", value: "Cancel", class: "white", id: "btn_close_member" }= t('views.collections.members.cancel')

app/views/places/_collapsed_member.haml
%td.member{style: 'cursor:pointer;', colspan: 6}
  .memberHeaderRow
    .memberHeaderColumn.collapsed{style: 'height:45px;width:280px;'}
      %img.members-collapse-icon{ko(click: :toggleExpanded, attr: {src: "'#{InsteddRails.url}/theme/images/icons/misc/black/arrowRight.png'"})}
      %span{ko(text: :userDisplayName, click: :toggleExpanded)}
      - if 'userPhoneNumber'
        %br/
        %span{ko(text: :userPhoneNumber), style: 'margin-left: 15px; font-size: 12px;'}


    - ['None', 'Read', 'Create', 'Update'].each do |permission|
      .permissionColumn.collapsed{ko(text: "summary#{permission}", css: "{ summaryAll: summary#{permission}() == window.t('javascripts.collections.members.permissions.all'), summarySome: summary#{permission}() == window.t('javascripts.collections.members.permissions.some') }"), style: 'height:42px;'}

    .permissionColumn.admin.collapsed{style: 'height:44px;'}
      %input{ko(checked: :admin), type: :checkbox}
    .lastColumn.collapsed{style: 'width:auto'}

app/views/places/_confirm_remove.haml
%a{ko(click: :open_confirm, visible: "!confirming()"), :class => "icon #{icon_class} black"}
  = action_description
%div.sbox.grey{ko(visible: :confirming), style: 'display:none;width:372px;'}
  %div.icon.fclose.black{ko(click: :close_confirm), style: 'width:24px;float:left;background-position: 0 -60px;'}
  %div{style: 'margin-top:8px;margin-left:28px;'}
    = confirm_action_prompt
    %hr
  %div{style:'height:37px;'}
    %a{ko(click: :confirm), :class => "button white right"}
      = 'Confirm'
    %a.grey.right{ko(click: :close_confirm), :style => 'margin-top:13px; margin-right:10px;'} Cancel

app/views/places/_edit_hierarchy.haml
%div{ko(visible: :showEditHierarchy), class: "box centered w40 rm-dialog", id: "frm_new_hierarchy", style: "margin-left: -180px; display: none; margin-top: -175px; box-shadow: 0 3px 11px -1px rgba(0, 0, 0, 0.3)" }
  %h2= t('views.places.edit_hierarchy')
  %div{:style => "margin-left: 132px;"}
    %span{ko(text: :nameError), :style => "color: red"}
  = t('views.places.name')
  %input#nameHierarchy{ko(value: :name, valueUpdate: :afterkeydown), :name => "email", :style => "margin-left: 88px; width: 250px;", :type => "text"}
  %br
  %br
  %div{:style => "margin-left: 132px;"}
    %span{ko(text: :codeError), :style => "color: red"}
  = t('views.places.code')
  %input#codeHierarchy{ko(value: :code, valueUpdate: :afterkeydown), :name => "phone_number", :style => "margin-left: 92px; width: 250px;", :type => "text"}
  %br
  %br

  %div{ style: "margin-left: 130px;"}
    %button{ko(click: '$root.updateHierarchy', css: {disabled: '$root.hasHierarachyError()'}), type: "button", value: "Save", class: "white", id: "btn_create_member" }= t('views.places.submit')
    
    %button{ko(click: '$root.hideEditHierarchy'), type: "button", value: "Cancel", class: "white", id: "btn_close_member" }= t('views.places.cancel')

app/views/places/_expanded_member.haml
%td.member{style: 'cursor:pointer;', colspan: 6}
  .memberHeaderRow
    .memberHeaderColumn{style: "width:285px;"}
      %img.members-collapse-icon{ko(click: :toggleExpanded, attr: {src: "'#{InsteddRails.url}/theme/images/icons/misc/black/arrow' + (expanded() ? 'Down' : 'Right') + '.png'"})}
      %span{ko(click: :toggleExpanded, text: :userDisplayName)}
      - if 'userPhoneNumber'
        %span{ko(text: :userPhoneNumber), style: 'font-size: 12px;'}

    - ['None', 'Read', 'Create', 'Update'].each do |permission|
      .permissionColumn{ko(text: "summary#{permission}", css: "{ summaryAll: summary#{permission}() == window.t('javascripts.collections.members.permissions.all'), summarySome: summary#{permission}() == window.t('javascripts.collections.members.permissions.some') }")}

    .permissionColumn.admin
      %input{ko(checked: :admin), type: :checkbox}

  .defaultLayerPermissionsRow
    .memberHeaderColumn{style: "width:272px;"}
      %hr.underlineExpandedMember
      .defaultLayerPermissionsTitle{ko(click: :toggleDefaultLayerPermissions)}
        %span{style: 'float:left'}
          %img.members-collapse-icon{ko(attr: {src: "defaultLayerPermissionsArrow('#{InsteddRails.url}')" })}
        %span.memberDetailsTitle
          = t('views.collections.members.default_permissions_for_all_layers')

    - ['None', 'Read', 'Create', 'Update'].each do |permission|
      .permissionColumn
        %hr.underlineExpandedMember
          %input{ko(disable: :admin, checked: "allLayers#{permission}", :attr => { "name" => "userId" }), :value => "all", :type => 'radio'}

    .permissionColumn.admin
      %hr.underlineExpandedMember

  /ko if: defaultLayerPermissionsExpanded
  /ko foreach: layers
  .layerRow
    .memberHeaderColumn{ko(text: "layerName()"), style: "width:218px;"}
    - ['None', 'Read', 'Create', 'Update'].each do |permission|
      .permissionColumn
        %input{ko(disable: "$parent.admin()", checked: "#{permission.downcase}Checked"), :value => "true", :type => 'radio'}
    .permissionColumn.admin
  //ko
  //ko

  / "REMOVE BECAUSE USER DON'T NEED THIS FEATURE"
  
  / .customPermissionsTitleRow
  /   .memberHeaderColumn{style: "width:285px;"}
  /     .frame
  /       .memberDetailsTitle{ko(text: 'site_permissions_title')}
  /   - ['None', 'Read', 'Create', 'Update'].each do |permission|
  /     .permissionColumn
  /       .frame
  /   .permissionColumn.admin
  /     .frame

  / /ko foreach: sitesWithCustomPermissions
  / .customPermissionRow
  /   .memberHeaderColumn{style: "width:285px;"}
  /     .frame
  /       .memberCustomPermissionsSiteName{ko(text: 'name')}
  /       %button.clist-remove.memberRemoveCustomPermissionSite{ko(click: "$parent.removeCustomPermission")}
  /       %hr.underlineExpandedMember{ko(visible: '$index() < $parent.sitesWithCustomPermissions().length - 1')}
  /   - ['None', 'Read', 'Create', 'Update'].each do |permission|
  /     .permissionColumn
  /       .frame
  /         %input{ko(disable: "$parent.admin", checked: "#{permission.downcase}Checked"), :value => "true", :type => 'radio'}
  /       %hr.underlineExpandedMember{ko(visible: '$index() < $parent.sitesWithCustomPermissions().length - 1')}
  /   .permissionColumn.admin
  /     .frame
  /       %hr.underlineExpandedMember{ko(visible: '$index() < $parent.sitesWithCustomPermissions().length - 1')}
  / //ko

  / .addCustomPermissionRow{ko(attr: { "id" => "customPermissionsAutocompleteId()" })}
  /   .memberHeaderColumn{style: "width:285px;"}
  /     .frame
  /       %input.autocomplete-site-input.ux-search{ ko(autocomplete: :customSite, value: :customSite, valueUpdate: :afterkeydown, source: "searchSitesUrl()", event: {keydown: :keyPress, blur: :save}), type: :text, placeholder: t('views.collections.members.add_custom_permissions_for_site') }
  /       %button.clist-add{ko(click: :createCustomPermissionForSite)}
  /   - ['None', 'Read', 'Create', 'Update'].each do |permission|
  /     .permissionColumn
  /   .permissionColumn.admin

  .removeMemberRow
    .memberHeaderColumn{style: 'width:573px'}
      = render 'places/confirm_remove', :action_description => t('views.collections.members.remove_this_member'), :icon_class => 'fdelete', :confirm_action_prompt => t('views.collections.members.remove_member_prompt')

app/views/places/index.haml
= render '/tabs'

- content_for :head do
  :javascript
    $(function() { initPlaces(#{current_user.id}, #{collection.id}, #{collection_admin?}, #{collection.layers.map{|x| {id: x.id, name: x.name}}.to_json}); });
  :css
    table.GralTable td.center { text-align: center; }

%script{type: "text/html", id: "field-hierarchy-items-template"}
  <!-- ko foreach: fieldHierarchyItems -->
  .hierarchy{ko(css: {active: 'selected()'}), style: "height: 24px;"}
    %a{ko(style: {marginLeft: "'' + (level * 20) + 'px'"}), href: 'javascript:void(0)'}
      <!-- ko if: id != '' -->
      %img{ko(click: :toggleExpand, attr: {src: "'#{InsteddRails.url}/theme/images/icons/18/black/folder' + (expanded() ? '_open' : '') + '.png'"}), style: 'position:relative;top:2px'}
      <!-- /ko -->
      %span{ko(click: :select, text: :name)}
    <!-- ko if: selected -->
    %button{ko(click: '$root.deleteHierarchy'), :class => "fdelete right", :style => "margin-top:0px", :type => "button"}
    %button{ko(click: '$root.editRegisterHierarchy'), :class => "fedit right", :style => "margin-top:0px", :type => "button"}
    %button{ko(click: '$root.showRegisterHierarchy'), :class => "fadd right", :style => "margin-top:0px", :type => "button"}
    <!-- /ko -->
  <!-- ko if: expanded -->
  <!-- ko template: {name: 'field-hierarchy-items-template', with: fieldHierarchyItems} -->
  <!-- /ko -->
  <!-- /ko -->
  <!-- /ko -->



.tabsline
  -if(current_user.admins? collection or current_user.is_national? collection)
    %h2= t('views.collections.overview.status')
    %div
      .sbox.grey.w30.sitesBox
        .left.sitesDescription
          .sitesCount= "#{collection.places.size}"
          = t('views.places.places')
        %button.csvDownload.white.right{type: "button", |
            onclick: "window.location = '#{download_collection_places_path()}'"}
          = t('views.places.download_hierarchy')
      %div
        = link_to t('views.places.upload_it_for_bulk_places_updates'), collection_import_hierarchy_wizard_path(collection), class: 'icon fexport black'
    %hr.clear/
    %br 
  #places-main
    %h2= t('views.places.title')
    %p= t('views.places.description')
    %br/

  .tablewrapp.w60.right
    %table.GralTable
      %colgroup
        %col{width: '300px'}
        %col{width: '60px'}
        %col{width: '60px'}
        %col{width: '60px'}
        %col{width: '60px'}
        %col{width: '60px'}
        %col{width: '1px'}
      %tr
        %th.members-tree{style: '-webkit-border-radius:8px 0 0 0;-moz-border-radius:8px 0 0 0;'} 
          = t('views.collections.members.member')
          &rarr; 
          = t('views.collections.members.site')
          &rarr; 
          = t('views.collections.members.layer')
        %th.members-permission= t('views.collections.members.none')
        %th.members-permission= t('views.collections.members.read')
        %th.members-permission= t('views.collections.members.create')
        %th.members-permission= t('views.collections.members.update')
        %th.members-permission= t('views.collections.members.admin')

      %tr{ :class => :membersFirstRow }
        %td
        %td
        %td
        %td
        %td
        %td
      /ko foreach: current_members
      /ko ifnot: isCurrentUser
      %tr{ko(css: { :expandedMember => :expanded }), :class => :membersRow}
        /ko if: expanded
        = render 'places/expanded_member'
        //ko

        /ko ifnot: expanded
        = render 'places/collapsed_member'
        //ko
      %tr
        %td{:colspan => 6, :style => 'height:5px;border-bottom:0px;'}
      //ko
      //ko
      - if collection_admin?
        = render 'places/add_member'
        = render 'places/add_non_existed_member'
        = render 'places/add_hierarchy'
        = render 'places/edit_hierarchy'

  .w30{:style => "width: 350px ! important;"}
    .hierarchy-long-container{tabIndex: 0, style: 'height:340px;box-shadow:none;'}
      <!-- ko template: {name: 'field-hierarchy-items-template', with: fieldHierarchyItems} -->
      <!-- /ko -->
  .clear